// Dados de seed para tabela motivosGlosa - Tabela 38 TISS (ANS)
// Total: 527 códigos

export const glosasSeedData: Array<{ codigo: string; descricao: string }> = [
  { codigo: "1001", descricao: "Número da carteira inválido." },
  { codigo: "1002", descricao: "Número do cartão nacional de saúde inválido. A admissão do beneficiário no prestador ocorreu antes da inclusão do beneficiário" },
  { codigo: "1003", descricao: "na operadora." },
  { codigo: "1004", descricao: "Solicitação anterior à inclusão do beneficiário." },
  { codigo: "1005", descricao: "Atendimento anterior à inclusão do beneficiário." },
  { codigo: "1006", descricao: "Atendimento após o desligamento do beneficiário." },
  { codigo: "1007", descricao: "Atendimento dentro da carência do beneficiário." },
  { codigo: "1008", descricao: "Assinatura divergente." },
  { codigo: "1009", descricao: "Beneficiário com pagamento em aberto." },
  { codigo: "1010", descricao: "Assinatura do titular / responsável inexistente." },
  { codigo: "1011", descricao: "Identificação do beneficiário não consistente." },
  { codigo: "1012", descricao: "Serviço profissional hospitalar não é coberto pelo plano do beneficiário." },
  { codigo: "1013", descricao: "Cadastro do beneficiário com problemas." },
  { codigo: "1014", descricao: "Beneficiário com data de exclusão." },
  { codigo: "1015", descricao: "Idade do beneficiário acima idade limite." },
  { codigo: "1016", descricao: "Beneficiário com atendimento suspenso." },
  { codigo: "1017", descricao: "Data validade da carteira vencida." },
  { codigo: "1018", descricao: "Empresa do beneficiário suspensa / excluída." },
  { codigo: "1019", descricao: "Família do beneficiário com atendimento suspenso." },
  { codigo: "1020", descricao: "Via de cartão do beneficiário cancelada." },
  { codigo: "1021", descricao: "Via de cartão do beneficiário não liberada." },
  { codigo: "1022", descricao: "Via de cartão do beneficiário não compatível." },
  { codigo: "1023", descricao: "Nome do titular inválido." },
  { codigo: "1024", descricao: "Plano não existente." },
  { codigo: "1025", descricao: "Beneficiário não possui cobertura para assistência odontológica." },
  { codigo: "1101", descricao: "Quantidade de guias informadas no protocolo diferente das cadastradas." },
  { codigo: "1102", descricao: "Protocolo é de reapresentação." },
  { codigo: "1103", descricao: "Protocolo não é de reapresentação." },
  { codigo: "1104", descricao: "Valor total do protocolo diferente do valor total das guias." },
  { codigo: "1201", descricao: "Atendimento fora da vigência do contrato com o credenciado." },
  { codigo: "1202", descricao: "Número do CNES inválido." },
  { codigo: "1203", descricao: "Código prestador inválido." },
  { codigo: "1204", descricao: "Admissão anterior à inclusão do credenciado na rede." },
  { codigo: "1205", descricao: "Admissão após o desligamento do credenciado da rede." },
  { codigo: "1206", descricao: "CPF/CNPJ inválido." },
  { codigo: "1207", descricao: "Credenciado não pertence à rede credenciada." },
  { codigo: "1208", descricao: "Solicitação anterior à inclusão do credenciado." },
  { codigo: "1209", descricao: "Solicitação após o desligamento do credenciado." },
  { codigo: "1210", descricao: "Solicitante credenciado não cadastrado." },
  { codigo: "1211", descricao: "Assinatura / carimbo do credenciado inexistente." },
  { codigo: "1212", descricao: "Atendimento / referência fora da vigência do contrato do prestador." },
  { codigo: "1213", descricao: "CBO (especialidade) inválido." },
  { codigo: "1214", descricao: "Credenciado não habilitado a realizar o procedimento." },
  { codigo: "1215", descricao: "Credenciado fora da abrangência geográfica do plano." },
  { codigo: "1216", descricao: "Especialidade não cadastrada." },
  { codigo: "1217", descricao: "Especialidade não cadastrada para o prestador." },
  { codigo: "1218", descricao: "Código de prestador incompatível com procedimento / exame cobrado." },
  { codigo: "1301", descricao: "Tipo guia inválido." },
  { codigo: "1302", descricao: "Código tipo guia principal e número guias incompatíveis." },
  { codigo: "1303", descricao: "Não existe o número guia principal informado." },
  { codigo: "1304", descricao: "Cobrança em guia indevida." },
  { codigo: "1305", descricao: "Item pago em outra guia." },
  { codigo: "1306", descricao: "Não existe número guia principal e/ou código guia principal." },
  { codigo: "1307", descricao: "Número da guia inválido." },
  { codigo: "1308", descricao: "Guia já apresentada." },
  { codigo: "1309", descricao: "Procedimento contratado não está de acordo com o tipo de guia utilizado." },
  { codigo: "1310", descricao: "Serviço do tipo cirúrgico e invasivo. Equipe médica não informada na guia." },
  { codigo: "1311", descricao: "Prestador executante não informado." },
  { codigo: "1312", descricao: "Prestador contratado não informado." },
  { codigo: "1313", descricao: "Guia com rasura." },
  { codigo: "1314", descricao: "Guia sem assinatura e/ou carimbo do credenciado." },
  { codigo: "1315", descricao: "Guia sem data do ato cirúrgico." },
  { codigo: "1316", descricao: "Guia com local de atendimento preenchido incorretamente." },
  { codigo: "1317", descricao: "Guia sem data do atendimento." },
  { codigo: "1318", descricao: "Guia com código de serviço preenchido incorretamente." },
  { codigo: "1319", descricao: "Guia sem assinatura do assistido." },
  { codigo: "1320", descricao: "Identificação do assistido incompleta." },
  { codigo: "1321", descricao: "Validade da guia expirada." },
  { codigo: "1322", descricao: "Comprovante presencial ou GTO não enviado." },
  { codigo: "1323", descricao: "Data preenchida incorretamente." },
  { codigo: "1401", descricao: "Acomodação não autorizada." },
  { codigo: "1402", descricao: "Procedimento não autorizado." },
  { codigo: "1403", descricao: "Não existe informação sobre a senha de autorização do procedimento." },
  { codigo: "1404", descricao: "Não existe guia de autorização relacionada." },
  { codigo: "1405", descricao: "Data de validade da senha é anterior à data do atendimento." },
  { codigo: "1406", descricao: "Número da senha informado diferente do liberado." },
  { codigo: "1407", descricao: "Serviço solicitado não possui cobertura." },
  { codigo: "1408", descricao: "Quantidade serviço solicitada acima da autorizada." },
  { codigo: "1409", descricao: "Quantidade serviço solicitada acima coberta." },
  { codigo: "1410", descricao: "Serviço solicitado em carência." },
  { codigo: "1411", descricao: "Solicitante não informado." },
  { codigo: "1412", descricao: "Problemas no sistema autorizador." },
  { codigo: "1413", descricao: "Acomodação não possui cobertura." },
  { codigo: "1414", descricao: "Data de validade da senha expirada." },
  { codigo: "1415", descricao: "Procedimento não autorizado para o beneficiário." },
  { codigo: "1416", descricao: "Solicitante não cadastrado." },
  { codigo: "1417", descricao: "Solicitante não habilitado." },
  { codigo: "1418", descricao: "Solicitante suspenso." },
  { codigo: "1419", descricao: "Serviço solicitado já autorizado." },
  { codigo: "1420", descricao: "Serviço solicitado fora da cobertura." },
  { codigo: "1421", descricao: "Serviço solicitado é de pré-existência." },
  { codigo: "1422", descricao: "Especialidade não cadastrada para o solicitante." },
  { codigo: "1423", descricao: "Quantidade solicitada acima da quantidade permitida." },
  { codigo: "1424", descricao: "Quantidade autorizada acima da quantidade permitida." },
  { codigo: "1425", descricao: "Necessita pré-autorização da empresa." },
  { codigo: "1426", descricao: "Não autorizado pela auditoria médica." },
  { codigo: "1427", descricao: "Necessidade de auditoria médica." },
  { codigo: "1428", descricao: "Falta de autorização da empresa de conectividade." },
  { codigo: "1429", descricao: "CBO-s (especialidade) não autorizado a realizar o serviço." },
  { codigo: "1430", descricao: "Procedimento odontológico não autorizado." },
  { codigo: "1431", descricao: "Procedimento não autorizado na face solicitada." },
  { codigo: "1432", descricao: "Procedimento não autorizado para dente/região solicitada." },
  { codigo: "1433", descricao: "Procedimento não autorizado, dente ausente." },
  { codigo: "1434", descricao: "Cobrança de conta de CTI neonatal na senha do parto." },
  { codigo: "1435", descricao: "Vigência do acordo posterior à data de realização do procedimento." },
  { codigo: "1436", descricao: "Cancelamento do acordo anterior à data de realização do procedimento." },
  { codigo: "1437", descricao: "Senha de autorização cancelada. Procedimento solicitado não autorizado por não atender a diretriz de utilização" },
  { codigo: "1438", descricao: "(DUT) do rol de procedimentos e eventos em saúde da ANS." },
  { codigo: "1501", descricao: "Tempo de evolução da doença inválido." },
  { codigo: "1502", descricao: "Tipo de doença inválido." },
  { codigo: "1503", descricao: "Indicador de acidente inválido." },
  { codigo: "1504", descricao: "Caráter de internação inválido." },
  { codigo: "1505", descricao: "Regime da internação inválido." },
  { codigo: "1506", descricao: "Tipo de internação inválido." },
  { codigo: "1507", descricao: "Urgência não aplicável." },
  { codigo: "1508", descricao: "Código CID não informado." },
  { codigo: "1509", descricao: "Código CID inválido." },
  { codigo: "1601", descricao: "Reincidência no atendimento." },
  { codigo: "1602", descricao: "Tipo de atendimento inválido ou não informado." },
  { codigo: "1603", descricao: "Tipo de consulta inválido." },
  { codigo: "1604", descricao: "Tipo de saída inválido." },
  { codigo: "1605", descricao: "Intervenção anterior à admissão." },
  { codigo: "1606", descricao: "Final da intervenção anterior ao início da intervenção." },
  { codigo: "1607", descricao: "Alta hospitalar anterior ao final da intervenção." },
  { codigo: "1608", descricao: "Alta anterior à data de internação." },
  { codigo: "1609", descricao: "Motivo saída inválido." },
  { codigo: "1610", descricao: "Óbito mulher inválido." },
  { codigo: "1611", descricao: "Intervenção anterior a internação." },
  { codigo: "1612", descricao: "Serviço não pode ser realizado no local especificado." },
  { codigo: "1613", descricao: "Consulta não autorizada." },
  { codigo: "1614", descricao: "Serviço ambulatorial não autorizado." },
  { codigo: "1615", descricao: "Internação não autorizada." },
  { codigo: "1701", descricao: "Cobrança fora do prazo de validade." },
  { codigo: "1702", descricao: "Cobrança de procedimento em duplicidade." },
  { codigo: "1703", descricao: "Horário do atendimento não está na faixa de urgência/emergência." },
  { codigo: "1704", descricao: "Valor cobrado superior ao acordado em pacote." },
  { codigo: "1705", descricao: "Valor apresentado a maior." },
  { codigo: "1706", descricao: "Valor apresentado a menor. Não existe informação sobre a tabela que será utilizada na valoração. Verifique o" },
  { codigo: "1707", descricao: "contrato do prestador." },
  { codigo: "1708", descricao: "Não existe valor para o procedimento realizado." },
  { codigo: "1709", descricao: "Falta prescrição médica." },
  { codigo: "1710", descricao: "Falta visto da enfermagem." },
  { codigo: "1711", descricao: "Procedimento pertence a um pacote acordado e já cobrado." },
  { codigo: "1712", descricao: "Assinatura do médico responsável pelo exame inexistente." },
  { codigo: "1713", descricao: "Faturamento inválido." },
  { codigo: "1714", descricao: "Valor do serviço superior ao valor de tabela." },
  { codigo: "1715", descricao: "Valor do serviço inferior ao valor de tabela." },
  { codigo: "1716", descricao: "Percentual de redução/acréscimo fora dos valores definidos em tabela." },
  { codigo: "1717", descricao: "Pago conforme relatório de auditoria externa - conta inicial." },
  { codigo: "1718", descricao: "Reanálise negada, pago conforme relatório auditoria." },
  { codigo: "1719", descricao: "Reanálise negada, análise conforme tabela acordada." },
  { codigo: "1720", descricao: "Liberados 150% de vídeo, sem cobertura para adicional de acomodação." },
  { codigo: "1721", descricao: "Código cobrado substituído pelo código pago." },
  { codigo: "1722", descricao: "Pago conforme negociação." },
  { codigo: "1723", descricao: "Adicional de urgência não previsto para atendimento clínico. Visita médica cobrada pela equipe cirúrgica incluída no período de 10 dias após" },
  { codigo: "1724", descricao: "realização do procedimento cirúrgico." },
  { codigo: "1725", descricao: "Valor pago a maior referente à taxa administrativa." },
  { codigo: "1726", descricao: "Valor apresentado a maior - plano individual." },
  { codigo: "1727", descricao: "Pago valor compatível com o procedimento." },
  { codigo: "1728", descricao: "Cobrança de material incluso no procedimento / exame realizado. Cobrança de material com valor acima do permitido para procedimento/exame" },
  { codigo: "1729", descricao: "realizado." },
  { codigo: "1730", descricao: "Filme incluso no exame realizado." },
  { codigo: "1731", descricao: "Taxa incompatível para atendimento ambulatorial." },
  { codigo: "1732", descricao: "QT com data de evento divergente da liberada." },
  { codigo: "1733", descricao: "Recuperação de valores por pagamento indevido." },
  { codigo: "1734", descricao: "Cobrado conta aberta, pago o pacote conforme negociação." },
  { codigo: "1735", descricao: "Cobrança de pacote não negociado com o prestador." },
  { codigo: "1736", descricao: "Conta aguardando negociação para pagamento." },
  { codigo: "1737", descricao: "Diferença deve ser cobrada do beneficiário pelo prestador como franquia." },
  { codigo: "1738", descricao: "Documento fiscal não enviado." },
  { codigo: "1739", descricao: "Duplicidade de conta devido a período cobrado já efetuado em outra parcial." },
  { codigo: "1740", descricao: "Estorno do valor de procedimento pago." },
  { codigo: "1741", descricao: "Honorário ou procedimento já pago a outro prestador." },
  { codigo: "1742", descricao: "Honorário ou procedimento já pago por reembolso ao beneficiário." },
  { codigo: "1743", descricao: "Não há negociação para cobrança do kit, discriminar por itens." },
  { codigo: "1744", descricao: "Negociação diferenciada devido a liminar." },
  { codigo: "1745", descricao: "Pagamento da equipe conforme relatório do cirurgião." },
  { codigo: "1746", descricao: "Percentual de acréscimo diferente do negociado. Plano do beneficiário e o tipo de acomodação não permitem acréscimo de" },
  { codigo: "1747", descricao: "honorários." },
  { codigo: "1748", descricao: "Procedimento não caracteriza urgência/emergência." },
  { codigo: "1749", descricao: "Relatório de auditoria não enviado na conta." },
  { codigo: "1801", descricao: "Procedimento inválido." },
  { codigo: "1802", descricao: "Procedimento incompatível com o sexo do beneficiário." },
  { codigo: "1803", descricao: "Idade do beneficiário incompatível com o procedimento." },
  { codigo: "1804", descricao: "Número de dias liberados / sessões autorizadas não informadas." },
  { codigo: "1805", descricao: "Valor total do procedimento diferente do valor processado." },
  { codigo: "1806", descricao: "Quantidade de procedimento deve ser maior que zero." },
  { codigo: "1807", descricao: "Procedimentos médicos duplicados." },
  { codigo: "1808", descricao: "Procedimento não conforme com CID." },
  { codigo: "1809", descricao: "Cobrança de procedimento não executado." },
  { codigo: "1810", descricao: "Cobrança de procedimento não solicitado pelo médico." },
  { codigo: "1811", descricao: "Procedimento sem registro de execução." },
  { codigo: "1812", descricao: "Cobrança de procedimento não correlacionado ao relatório específico. Cobrança de procedimento sem justificativa para realização ou com justificativa" },
  { codigo: "1813", descricao: "insuficiente." },
  { codigo: "1814", descricao: "Cobrança de procedimento com data de autorização posterior à do atendimento." },
  { codigo: "1815", descricao: "Procedimento não autorizado. Cobrança de procedimento em quantidade incompatível com o" },
  { codigo: "1816", descricao: "procedimento/evolução clínica." },
  { codigo: "1817", descricao: "Cobrança de procedimento incluso no procedimento principal." },
  { codigo: "1818", descricao: "Cobrança de procedimento que exige autorização prévia. Cobrança de procedimento com história clínica/hipótese diagnóstica não" },
  { codigo: "1819", descricao: "compatível." },
  { codigo: "1820", descricao: "Cobrança de procedimento em quantidade acima da máxima permitida/autorizada." },
  { codigo: "1821", descricao: "Cobrança de procedimento não compatível com a idade." },
  { codigo: "1822", descricao: "Cobrança de procedimento com ausência de resultado ou laudo técnico. Procedimento realizado pelo mesmo profissional, na mesma especialidade, no prazo" },
  { codigo: "1823", descricao: "inferior ao estipulado sem justificativa adequada." },
  { codigo: "1824", descricao: "Procedimento cobrado não corresponde ao exame executado. Cobrança de procedimento ambulatorial com data de autorização posterior à do" },
  { codigo: "1825", descricao: "atendimento. Vias de acesso dos procedimentos cobrados não estão previstas na listagem de" },
  { codigo: "1826", descricao: "procedimentos múltiplos. Cobrança de outro procedimento em outra guia, na mesma data, pelo mesmo profissional com mesmo grau de participação - liberado valor referente à via de" },
  { codigo: "1827", descricao: "acesso do procedimento secundário." },
  { codigo: "1828", descricao: "Adicional de urgência não previsto para procedimento cirúrgico eletivo." },
  { codigo: "1829", descricao: "Adicional de vídeo não previsto para o procedimento. Cobrança de procedimento sem informação das datas de atendimento- visita," },
  { codigo: "1830", descricao: "plantão, intensivista, avaliação enteral/parenteral." },
  { codigo: "1831", descricao: "Laudo do exame enviado não justifica a cobrança do procedimento." },
  { codigo: "1832", descricao: "Procedimento não permite cobrança de auxiliar de anestesista." },
  { codigo: "1833", descricao: "Procedimento cobrado não permite acréscimo de acomodação." },
  { codigo: "1834", descricao: "Porte anestésico cobrado incompatível com o porte do procedimento realizado. \"Analgesia por dia subsequente\" não justificada em relatório médico, para o" },
  { codigo: "1835", descricao: "procedimento realizado e/ou data do atendimento. \"Analgesia por dia subsequente\" incompatível com a via de administração do" },
  { codigo: "1836", descricao: "medicamento - vo ou iv periférica - sendo liberada visita hospitalar." },
  { codigo: "1837", descricao: "Não cabe pagamento do honorário integral por ser via de acesso cirúrgico diferente." },
  { codigo: "1838", descricao: "Grau de participação informado incompatível com evento cobrado." },
  { codigo: "1839", descricao: "Necessário envio do resultado do exame anátomo patológico." },
  { codigo: "1840", descricao: "Procedimento executado antes da autorização." },
  { codigo: "1901", descricao: "Acomodação inválida." },
  { codigo: "1902", descricao: "Acomodação informada não está de acordo com acomodação contratada." },
  { codigo: "1903", descricao: "Permanência hospitalar incompatível com a evolução clínica." },
  { codigo: "1904", descricao: "Permanência hospitalar incompatível com o procedimento autorizado" },
  { codigo: "1905", descricao: "Quantidade de diárias deve ser maior que zero." },
  { codigo: "1906", descricao: "Acomodação não informada." },
  { codigo: "1907", descricao: "Quantidade UTI não prevista para procedimento." },
  { codigo: "1908", descricao: "Usuário não possui cobertura de UTI." },
  { codigo: "1909", descricao: "Acomodação não autorizada." },
  { codigo: "1910", descricao: "Cobrança de diárias em locais de acomodações diferentes, no mesmo dia." },
  { codigo: "1911", descricao: "Permanência hospitalar para investigação injustificada." },
  { codigo: "1912", descricao: "Evolução clínica não compatível com a permanência em UTI." },
  { codigo: "1913", descricao: "Código de diária incompatível com o local de atendimento." },
  { codigo: "1914", descricao: "Cobrança de diária em quantidade incompatível com a permanência hospitalar. Mudança de acomodação sem comunicação ao paciente, familiar ou acompanhante," },
  { codigo: "1915", descricao: "ou sem solicitação destes." },
  { codigo: "1916", descricao: "Cobrança de diárias de UTI incompatível com diagnóstico e evolução clínica." },
  { codigo: "1917", descricao: "Falta prorrogação para quantidade de diárias cobradas." },
  { codigo: "1918", descricao: "Plano do beneficiário não contempla diária de acompanhante." },
  { codigo: "2001", descricao: "Material inválido." },
  { codigo: "2002", descricao: "Material sem cobertura para atendimento ambulatorial." },
  { codigo: "2003", descricao: "Material não especificado." },
  { codigo: "2004", descricao: "Material sem nota fiscal do fornecedor." },
  { codigo: "2005", descricao: "Quantidade de material deve ser maior que zero." },
  { codigo: "2006", descricao: "Material informado não coberto." },
  { codigo: "2007", descricao: "Cobrança de material em quantidade incompatível com a permanência. Cobrança de material em quantidades incompatíveis com o procedimento" },
  { codigo: "2008", descricao: "realizado." },
  { codigo: "2009", descricao: "Quantidade de material superior à quantidade coberta." },
  { codigo: "2010", descricao: "Cobrança de materiais inclusos nas taxas." },
  { codigo: "2011", descricao: "Cobrança de material incluso no pacote negociado." },
  { codigo: "2012", descricao: "Cobrança de material incompatível com o relatório técnico." },
  { codigo: "2013", descricao: "Cobrança de material em permanência hospitalar não autorizada." },
  { codigo: "2014", descricao: "Cobrança de material não utilizado." },
  { codigo: "2015", descricao: "Material não autorizado." },
  { codigo: "2101", descricao: "Medicamento inválido." },
  { codigo: "2102", descricao: "Medicamento sem cobertura para atendimento ambulatorial." },
  { codigo: "2103", descricao: "Medicamento não especificado." },
  { codigo: "2104", descricao: "Medicamento sem nota fiscal do fornecedor." },
  { codigo: "2105", descricao: "Quantidade de medicamentos deve ser maior que zero." },
  { codigo: "2106", descricao: "Medicamento informado não coberto." },
  { codigo: "2107", descricao: "Cobrança de medicamento em quantidade incompatível com a permanência. Cobrança de medicamento em quantidades incompatíveis com o procedimento" },
  { codigo: "2108", descricao: "realizado." },
  { codigo: "2109", descricao: "Quantidade de medicamento superior à quantidade coberta." },
  { codigo: "2110", descricao: "Cobrança de medicamentos inclusos nas taxas." },
  { codigo: "2111", descricao: "Cobrança de medicamento incluso no pacote negociado." },
  { codigo: "2112", descricao: "Cobrança de medicamento incompatível com o relatório técnico." },
  { codigo: "2113", descricao: "Cobrança de medicamento em permanência hospitalar não autorizada." },
  { codigo: "2114", descricao: "Cobrança de medicamento não utilizado." },
  { codigo: "2115", descricao: "Medicamento não autorizado." },
  { codigo: "2201", descricao: "OPME inválido." },
  { codigo: "2202", descricao: "OPME sem cobertura para atendimento ambulatorial." },
  { codigo: "2203", descricao: "OPME sem nota fiscal do fornecedor." },
  { codigo: "2204", descricao: "Quantidade de OPME deve ser maior que zero." },
  { codigo: "2205", descricao: "OPME informado não coberto." },
  { codigo: "2206", descricao: "OPME informado não autorizado." },
  { codigo: "2207", descricao: "Cobrança de OPME não utilizado." },
  { codigo: "2208", descricao: "Cobrança de OPME no item material e medicamentos." },
  { codigo: "2209", descricao: "Cobrança de OPME em desacordo com relatório técnico." },
  { codigo: "2210", descricao: "Cobrança de OPME em quantidade incompatível com o procedimento realizado." },
  { codigo: "2211", descricao: "Cobrança de OPME inclusa no pacote." },
  { codigo: "2212", descricao: "OPME em desacordo com os critérios técnicos adotados pela operadora." },
  { codigo: "2213", descricao: "OPME pago a fornecedor terceirizado." },
  { codigo: "2301", descricao: "Gases medicinais inválidos." },
  { codigo: "2302", descricao: "Cobrança de oxigenoterapia sem prescrição médica. Cobrança de oxigenoterapia com quantitativo de uso em divergência/pago valor" },
  { codigo: "2303", descricao: "corrigido." },
  { codigo: "2304", descricao: "Cobrança de oxigênio incluso na taxa de nebulização especificada." },
  { codigo: "2305", descricao: "Cobrança de oxigenoterapia em uso prolongado sem justificativa de uso." },
  { codigo: "2306", descricao: "Cobrança de oxigenoterapia sem registro de controle de uso (entrada e saída)." },
  { codigo: "2307", descricao: "Cobrança de gases em quantidade superior ao período de permanência. Cobrança de co2 nas cirurgias videolaparoscópicas durante toda a realização do" },
  { codigo: "2308", descricao: "procedimento (início ao fim)." },
  { codigo: "2309", descricao: "Cobrança de ar comprimido sem registro no boletim anestésico e duração de uso." },
  { codigo: "2310", descricao: "Cobrança de gases incompatível com o utilizado/ prescrito." },
  { codigo: "2401", descricao: "Taxa / aluguel inválido. Cobrança de taxa por uso de equipamento incompatível com o procedimento" },
  { codigo: "2402", descricao: "realizado/uso previsto no procedimento." },
  { codigo: "2403", descricao: "Cobrança de taxa de uso de bomba de infusão em paciente internado na UTI." },
  { codigo: "2404", descricao: "Cobrança de outras taxas associadas/inclusas na cobrança da taxa de sala prevista. Cobrança de mais de uma taxa de sala de cirurgia, por conta do número de" },
  { codigo: "2405", descricao: "procedimentos realizados no mesmo tempo cirúrgico." },
  { codigo: "2406", descricao: "Cobrança indevida de taxa de sala por administração de medicamentos. Cobrança de taxas, de serviços realizados em ambientes incompatíveis com o uso de" },
  { codigo: "2407", descricao: "equipamentos." },
  { codigo: "2408", descricao: "Cobrança de taxas em quantidade superior ao tempo de permanência hospitalar. Cobrança de taxa de observação em pronto socorro com permanência menor que o" },
  { codigo: "2409", descricao: "período estipulado." },
  { codigo: "2410", descricao: "Cobrança de taxa de observação em pronto socorro sem o registro da permanência." },
  { codigo: "2411", descricao: "Cobrança de taxa de sala de pronto socorro, para aplicação de medicamentos." },
  { codigo: "2412", descricao: "Cobrança de taxa de recuperação anestésica não justificada para o procedimento." },
  { codigo: "2413", descricao: "Cobrança de taxa inclusa no pacote negociado. Cobrança de taxa de equipamento em concomitância com a cobrança de taxa para" },
  { codigo: "2414", descricao: "o procedimento." },
  { codigo: "2415", descricao: "Taxa exige informação do valor na guia. Cobrança de taxa de recuperação anestésica para pacientes com pós- operatório" },
  { codigo: "2416", descricao: "imediato realizado na UTI/CTI." },
  { codigo: "2417", descricao: "Cobrança de taxa de recuperação anestésica sem a presença do anestesista." },
  { codigo: "2418", descricao: "Cobrança de taxa de sala incompatível com o procedimento." },
  { codigo: "2419", descricao: "Cobrança de taxa de observação para atendimento que gerou uma internação. Cobrança de taxa de sala cirúrgica com porte anestésico diferente do procedimento" },
  { codigo: "2420", descricao: "autorizado/realizado." },
  { codigo: "2421", descricao: "Cobrança de taxa em quantidade incorreta. Cobrança de taxa por uso de equipamento de uso obrigatório na sala de cirurgia," },
  { codigo: "2422", descricao: "cuja taxa de sala cirúrgica já inclui seu uso." },
  { codigo: "2423", descricao: "Cobrança de taxa de equipamentos de uso obrigatório no local de atendimento." },
  { codigo: "2424", descricao: "Cobrança de taxa de observação para atendimento que gerou uma internação." },
  { codigo: "2501", descricao: "Procedimento em série inválido." },
  { codigo: "2502", descricao: "Cobrança de duas avaliações fisioterápicas. Cobrança de psicoterapia individual, quando o aplicado é a cobrança de" },
  { codigo: "2503", descricao: "psicoterapia em grupo. Quantidade de sessões cobradas não condizem com as assinaturas no controle de" },
  { codigo: "2504", descricao: "tratamento seriado." },
  { codigo: "2505", descricao: "O código cobrado é diferente do código autorizado." },
  { codigo: "2506", descricao: "A quantidade de sessões cobradas é diferente da quantidade autorizada." },
  { codigo: "2507", descricao: "O código autorizado está incompatível com a prescrição médica solicitada. Cobrança de sessões sem o devido plano de tratamento e, ou, com o prazo de" },
  { codigo: "2508", descricao: "pagamento expirado." },
  { codigo: "2509", descricao: "Cobrança do procedimento seriado incompatível com o quadro clínico. Cobrança do procedimento seriado em número de sessões acima da quantidade" },
  { codigo: "2510", descricao: "estabelecida." },
  { codigo: "2511", descricao: "Ausência de evolução no prontuário médico do tratamento seriado realizado. Cobrança de sessões de fisioterapia em desacordo com as evoluções do prontuário" },
  { codigo: "2512", descricao: "médico." },
  { codigo: "2513", descricao: "Cobrança de tratamento seriado sem justificativa clínica/técnica." },
  { codigo: "2514", descricao: "Serviço não contratado para o prestador." },
  { codigo: "2515", descricao: "Local de atendimento inadequado." },
  { codigo: "2516", descricao: "Quantidade cobrada diferente da realizada." },
  { codigo: "2601", descricao: "Codificação incorreta/inadequada do procedimento." },
  { codigo: "2602", descricao: "Cobrança de honorário incluso no procedimento principal." },
  { codigo: "2603", descricao: "Cobrança de honorário sem registro da efetiva participação do profissional." },
  { codigo: "2604", descricao: "Procedimento principal não requer equipe médica." },
  { codigo: "2605", descricao: "Não cabe pagamento do honorário integral por ser a mesma via de acesso cirúrgico." },
  { codigo: "2606", descricao: "Cobrança do honorário em local de atendimento incorreto (inexistente)." },
  { codigo: "2607", descricao: "Cobrança de honorários em duplicidade. Cobrança de consulta indevida, quando o procedimento principal já está sendo" },
  { codigo: "2608", descricao: "remunerado." },
  { codigo: "2609", descricao: "Local de atendimento não informado." },
  { codigo: "2610", descricao: "Grau de participação de auxiliar incompatível com procedimento cobrado." },
  { codigo: "2611", descricao: "Cobrança de especialista não justificada no evento. Cobrança indevida de equipe \"stand-by\", já que angioplastia seguida de cirurgia" },
  { codigo: "2612", descricao: "cardíaca." },
  { codigo: "2613", descricao: "Honorário médico do anestesista já liberado no procedimento cirúrgico, pois \"analgesia por dia subsequente\" cobrada na mesma data do evento cirúrgico." },
  { codigo: "2614", descricao: "Cobrança de cada participante da equipe deve ser feita em guias diferentes." },
  { codigo: "2701", descricao: "Procedimento inválido." },
  { codigo: "2702", descricao: "Cobrança de exame não solicitado pelo médico." },
  { codigo: "2703", descricao: "Exame sem registro de execução." },
  { codigo: "2704", descricao: "Cobrança de exame não correlacionado ao relatório específico. Cobrança de procedimento/exame sem justificativa para realização ou com" },
  { codigo: "2705", descricao: "justificativa insuficiente. Cobrança de procedimento/exame com data de autorização posterior à do" },
  { codigo: "2706", descricao: "atendimento." },
  { codigo: "2707", descricao: "Exame não autorizado. Cobrança de exame em quantidade incompatível com o procedimento/evolução" },
  { codigo: "2708", descricao: "clínica." },
  { codigo: "2709", descricao: "Cobrança de procedimento incluso no procedimento principal." },
  { codigo: "2710", descricao: "Cobrança de exame que exige autorização prévia." },
  { codigo: "2711", descricao: "Cobrança de exame com história clínica/hipótese diagnóstica não compatível." },
  { codigo: "2712", descricao: "Cobrança de exame em quantidade acima da máxima permitida/autorizada." },
  { codigo: "2713", descricao: "Cobrança de exame não compatível com a idade." },
  { codigo: "2714", descricao: "Cobrança de exame com ausência de resultado ou laudo técnico. Exame realizado pelo mesmo profissional, na mesma especialidade, no prazo" },
  { codigo: "2715", descricao: "inferior ao estipulado sem justificativa adequada." },
  { codigo: "2716", descricao: "Exame cobrado não corresponde ao exame executado. Cobrança de exame ambulatorial com data de autorização posterior à do" },
  { codigo: "2717", descricao: "atendimento." },
  { codigo: "2718", descricao: "Exames não justificam caráter de urgência." },
  { codigo: "2801", descricao: "Pacote inválido." },
  { codigo: "2802", descricao: "Pacote incompatível com o sexo do beneficiário." },
  { codigo: "2803", descricao: "Idade do beneficiário incompatível com o pacote." },
  { codigo: "2804", descricao: "Valor total do pacote diferente do valor processado." },
  { codigo: "2805", descricao: "Valor do pacote superior ao valor dos itens." },
  { codigo: "2806", descricao: "Cobrança de pacote não executado." },
  { codigo: "2807", descricao: "Cobrança de pacote não solicitado pelo médico." },
  { codigo: "2808", descricao: "Pacote sem registro de execução." },
  { codigo: "2809", descricao: "Cobrança de pacote não correlacionado ao relatório específico. Cobrança de pacote sem justificativa para realização ou com justificativa" },
  { codigo: "2810", descricao: "insuficiente." },
  { codigo: "2811", descricao: "Cobrança de pacote com data de autorização posterior à do atendimento." },
  { codigo: "2812", descricao: "Pacote não autorizado. Cobrança de pacote em quantidade incompatível com o procedimento/evolução" },
  { codigo: "2813", descricao: "clínica." },
  { codigo: "2814", descricao: "Itens de composição do pacote não realizados." },
  { codigo: "2815", descricao: "Cobrança do pacote exige autorização prévia." },
  { codigo: "2816", descricao: "Cobrança de pacote com história clínica/hipótese diagnóstica não compatível." },
  { codigo: "2817", descricao: "Cobrança de pacote em quantidade acima da máxima permitida/autorizada." },
  { codigo: "2818", descricao: "Cobrança de pacote não compatível com a idade." },
  { codigo: "2819", descricao: "Cobrança de pacote com ausência de resultado ou laudo técnico. Pacote realizado pelo mesmo profissional, na mesma especialidade, no prazo" },
  { codigo: "2820", descricao: "inferior ao estipulado sem justificativa adequada." },
  { codigo: "2821", descricao: "Pacote cobrado não corresponde ao exame executado. Cobrança de pacote ambulatorial com data de autorização posterior à do" },
  { codigo: "2822", descricao: "atendimento." },
  { codigo: "2901", descricao: "Revisão de glosa inválida." },
  { codigo: "2902", descricao: "Glosa mantida." },
  { codigo: "2903", descricao: "Pedido de revisão sem justificativa." },
  { codigo: "2904", descricao: "Mais de um recurso de glosa para a mesma guia/protocolo." },
  { codigo: "2905", descricao: "A guia não é de revisão." },
  { codigo: "2906", descricao: "Número da guia inválido." },
  { codigo: "2907", descricao: "Prazo de 180 dias ultrapassado para solicitação de reanálise." },
  { codigo: "2908", descricao: "Solicitação de reanálise efetuada de forma incorreta." },
  { codigo: "2909", descricao: "Prazo para solicitação de recurso de glosa prescrito." },
  { codigo: "3001", descricao: "Procedimento odontológico inválido." },
  { codigo: "3002", descricao: "Cobrança de procedimento odontológico que exige autorização prévia." },
  { codigo: "3003", descricao: "Idade do beneficiário incompatível com o procedimento odontológico. Cobrança de procedimento odontológico em quantidade acima da máxima" },
  { codigo: "3004", descricao: "permitida/autorizada." },
  { codigo: "3005", descricao: "Valor total do procedimento diferente do valor processado." },
  { codigo: "3006", descricao: "Quantidade de procedimento deve ser maior que zero." },
  { codigo: "3007", descricao: "Procedimentos odontológicos duplicados." },
  { codigo: "3008", descricao: "Cobrança de procedimento odontológico incluso no procedimento principal." },
  { codigo: "3009", descricao: "Cobrança de procedimento odontológico não executado." },
  { codigo: "3010", descricao: "Cobrança de procedimento não solicitado pelo cirurgião-dentista." },
  { codigo: "3011", descricao: "Procedimento odontológico sem registro de execução." },
  { codigo: "3012", descricao: "Cobrança de procedimento odontológico não correlacionado ao relatório específico. Cobrança de procedimento odontológico sem justificativa para realização ou com" },
  { codigo: "3013", descricao: "justificativa insuficiente. Cobrança de procedimento odontológico com data de autorização posterior à do" },
  { codigo: "3014", descricao: "atendimento. Cobrança de procedimento odontológico com ausência de resultado ou laudo" },
  { codigo: "3015", descricao: "técnico. Procedimento odontológico realizado pelo mesmo profissional, na mesma" },
  { codigo: "3016", descricao: "especialidade, no prazo inferior ao estipulado sem justificativa adequada." },
  { codigo: "3017", descricao: "Procedimento cobrado não corresponde a perícia (especificar)." },
  { codigo: "3018", descricao: "Evento glosado por auditoria (especificar) Evento sob análise técnica, aguardando liberação de confirmação para posterior" },
  { codigo: "3019", descricao: "pagamento." },
  { codigo: "3020", descricao: "Conforme documentação radiográfica enviada, evento realizado inadequadamente." },
  { codigo: "3021", descricao: "Falha em informação de dados de arcadas/hemi-arcos." },
  { codigo: "3022", descricao: "Falha em informação de dados de dente inicial e/ou final." },
  { codigo: "3023", descricao: "Falha em informação de dados de faces dos dentes." },
  { codigo: "3024", descricao: "Evento só possível em dentes decíduos." },
  { codigo: "3025", descricao: "Evento só possível em dentes permanentes." },
  { codigo: "3026", descricao: "Erro nas informações de ordem dos dentes inicial e final." },
  { codigo: "3027", descricao: "Desacordo entre o tipo de dente e o número de canais solicitados." },
  { codigo: "3028", descricao: "Evento restrito à especialistas." },
  { codigo: "3029", descricao: "Evento não indicado pela auditoria inicial." },
  { codigo: "3030", descricao: "Auditoria final consta que a restauração foi realizada em outro material." },
  { codigo: "3031", descricao: "Radiografia fora dos padrões técnicos." },
  { codigo: "3032", descricao: "Intervalo da última MPP inferior a três meses." },
  { codigo: "3033", descricao: "Intervalo da última MPP inferior a quatro meses." },
  { codigo: "3034", descricao: "Justificativa tecnicamente não satisfatória." },
  { codigo: "3035", descricao: "Paciente em tratamento com o mesmo profissional." },
  { codigo: "3036", descricao: "Paciente em tratamento com outro profissional." },
  { codigo: "3037", descricao: "Procedimento cobrado não é igual ao executado." },
  { codigo: "3038", descricao: "Radiografia inicial incongruente com a radiografia final." },
  { codigo: "3039", descricao: "Radiografia não corresponde ao procedimento cobrado." },
  { codigo: "3040", descricao: "Glosa técnica (especificar detalhadamente)." },
  { codigo: "3041", descricao: "Aguardando documentação de ortodontia." },
  { codigo: "3042", descricao: "Após análise da radiografia inicial verificou-se exodontia de incluso." },
  { codigo: "3043", descricao: "Após análise da radiografia inicial verificou-se exodontia de semi-incluso." },
  { codigo: "3044", descricao: "Após análise da radiografia inicial verificou-se exodontia simples." },
  { codigo: "3045", descricao: "Após análise da radiografia inicial, verificou-se exodontia de fragmento radicular." },
  { codigo: "3046", descricao: "Auditoria final consta que o procedimento foi realizado com outro material." },
  { codigo: "3047", descricao: "Ausência de imagem/foto/radiografia/ diagnóstico pós-procedimento odontológico." },
  { codigo: "3048", descricao: "Cancelamento do procedimento odontológico por solicitação do beneficiário." },
  { codigo: "3049", descricao: "Cancelamento do procedimento odontológico por solicitação do prestador." },
  { codigo: "3050", descricao: "Cobrança de urgência/emergência na vigência do tratamento odontológico." },
  { codigo: "3051", descricao: "Documentação em análise." },
  { codigo: "3052", descricao: "Documentação incompleta, incorreta ou ausente." },
  { codigo: "3053", descricao: "Elementos podem ser visualizados em uma mesma película." },
  { codigo: "3054", descricao: "Identificado conduto(s) não obturado(s)." },
  { codigo: "3055", descricao: "Identificado tratamento endodôntico e não retratamento." },
  { codigo: "3056", descricao: "Na auditoria foi constatada divergência na quantidade de faces restauradas." },
  { codigo: "3057", descricao: "Não apresenta a quantidade mínima de elementos dentários por segmento." },
  { codigo: "3058", descricao: "Necessária auditoria final." },
  { codigo: "3059", descricao: "Necessária auditoria inicial." },
  { codigo: "3060", descricao: "Necessária auditoria intermediária." },
  { codigo: "3061", descricao: "Necessária avaliação do especialista." },
  { codigo: "3062", descricao: "Necessário enviar laudo ou relatório técnico sobre o tratamento solicitado." },
  { codigo: "3063", descricao: "O plano de tratamento autorizado será cancelado devido à troca de profissional." },
  { codigo: "3064", descricao: "Procedimento autorizado apenas para dentes tratados endodonticamente." },
  { codigo: "3065", descricao: "Procedimento autorizado somente para dentes anteriores. Procedimento em desacordo com o anexo guia tratamento odontológico situação" },
  { codigo: "3066", descricao: "inicial." },
  { codigo: "3067", descricao: "Radiografia final não enviada." },
  { codigo: "3068", descricao: "Radiografia final sem dissociação dos condutos." },
  { codigo: "3069", descricao: "Radiografia indica a necessidade de tratamento endodôntico." },
  { codigo: "3070", descricao: "Radiografia indica a presença de raiz residual no alvéolo." },
  { codigo: "3071", descricao: "Radiografia indica ausência de núcleo." },
  { codigo: "3072", descricao: "Radiografia indica canal (ais) não obturado(s)." },
  { codigo: "3073", descricao: "Radiografia indica desvio da trajetória do canal." },
  { codigo: "3074", descricao: "Radiografia indica excesso de material." },
  { codigo: "3075", descricao: "Radiografia indica falha na obturação do(s) conduto(s)." },
  { codigo: "3076", descricao: "Radiografia indica falta de adaptação da coroa/núcleo." },
  { codigo: "3077", descricao: "Radiografia indica falta de adaptação da coroa/peça protética." },
  { codigo: "3078", descricao: "Radiografia indica núcleo inadequado." },
  { codigo: "3079", descricao: "Radiografia indica tratamento endodôntico e não retratatamento endodôntico." },
  { codigo: "3080", descricao: "Radiografia inicial e final não enviada." },
  { codigo: "3081", descricao: "Radiografia inicial não enviada." },
  { codigo: "3082", descricao: "Radiografia/imagem indica falha na restauração. Reavaliar o plano de tratamento observando critérios de indicação, oportunidade e" },
  { codigo: "3083", descricao: "viabilidade." },
  { codigo: "3084", descricao: "Relatório analise técnica sem carimbo/assinatura do prestador." },
  { codigo: "3085", descricao: "Radiografia não corresponde ao procedimento solicitado." },
  { codigo: "3086", descricao: "Tratamento odontológico não caracterizado como urgência." },
  { codigo: "5001", descricao: "Mensagem eletrônica fora do Padrão TISS." },
  { codigo: "5002", descricao: "Não foi possível validar o arquivo XML." },
  { codigo: "5003", descricao: "Endereço do remetente inválido." },
  { codigo: "5004", descricao: "Endereço do destinatário inválido." },
  { codigo: "5005", descricao: "Remetente não identificado." },
  { codigo: "5006", descricao: "Destinatário não identificado." },
  { codigo: "5007", descricao: "Mensagem inconsistente ou incompleta." },
  { codigo: "5008", descricao: "Espaço reservado para a caixa de saída insuficiente." },
  { codigo: "5009", descricao: "Espaço reservado para a caixa de entrada insuficiente." },
  { codigo: "5010", descricao: "Envio de mensagem não foi terminado." },
  { codigo: "5011", descricao: "Envio de mensagem finalizada." },
  { codigo: "5012", descricao: "Recebimento de mensagem não finalizado." },
  { codigo: "5013", descricao: "Recebimento de mensagem finalizada." },
  { codigo: "5014", descricao: "Código HASH inválido. Mensagem pode estar corrompida." },
  { codigo: "5015", descricao: "permitido. Sem nenhuma ocorrência de movimento de inclusão na competência para envio a" },
  { codigo: "5016", descricao: "ANS." },
  { codigo: "5017", descricao: "Arquivo processado pela ANS." },
  { codigo: "5018", descricao: "Certificado digital inválido." },
  { codigo: "5019", descricao: "Certificado digital vencido." },
  { codigo: "5020", descricao: "Certificado digital revogado." },
  { codigo: "5021", descricao: "Cadeia de certificação inválida." },
  { codigo: "5022", descricao: "Assinatura digital não confere." },
  { codigo: "5023", descricao: "Competência não está liberada para envio de dados." },
  { codigo: "5024", descricao: "Operadora inativa na competência dos dados." },
  { codigo: "5025", descricao: "Data de registro da transação inválida." },
  { codigo: "5026", descricao: "Hora de registro da transação inválida." },
  { codigo: "5027", descricao: "Registro ANS da operadora inválido." },
  { codigo: "5028", descricao: "Versão do padrão inválida." },
  { codigo: "5029", descricao: "Indicador inválido." },
  { codigo: "5030", descricao: "Código do munícipio inválido." },
  { codigo: "5031", descricao: "Caráter de atendimento inválido." },
  { codigo: "5032", descricao: "Indicador de recém-nato inválido." },
  { codigo: "5033", descricao: "Motivo de encerramento inválido." },
  { codigo: "5034", descricao: "Valor não informado." },
  { codigo: "5035", descricao: "Código da tabela de referência não informado." },
  { codigo: "5036", descricao: "Código do grupo do procedimento inválido." },
  { codigo: "5037", descricao: "Código do dente inválido." },
  { codigo: "5038", descricao: "Código da região da boca inválido." },
  { codigo: "5039", descricao: "Código da face do dente inválido." },
  { codigo: "5040", descricao: "Valor deve ser maior que zero." },
  { codigo: "5041", descricao: "Quantidade não informada." },
  { codigo: "5042", descricao: "Valor informado da guia diferente do somatório do valor informado dos itens." },
  { codigo: "5043", descricao: "Motivo inválido." },
  { codigo: "5044", descricao: "Já existem informações na ANS para a competência informada." },
  { codigo: "5045", descricao: "Competência anterior não enviada." },
  { codigo: "5046", descricao: "Competência inválida." },
];
