-- Seed da tabela motivosGlosa com códigos TISS oficiais (Tabela 38 ANS)
-- Total: 527 códigos

DELETE FROM motivosGlosa;

INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1001', 'Número da carteira inválido.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1002', 'Número do cartão nacional de saúde inválido.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1003', 'A admissão do beneficiário no prestador ocorreu antes da inclusão do beneficiário na operadora.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1004', 'Solicitação anterior à inclusão do beneficiário.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1005', 'Atendimento anterior à inclusão do beneficiário.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1006', 'Atendimento após o desligamento do beneficiário.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1007', 'Atendimento dentro da carência do beneficiário.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1008', 'Assinatura divergente.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1009', 'Beneficiário com pagamento em aberto.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1010', 'Assinatura do titular / responsável inexistente.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1011', 'Identificação do beneficiário não consistente.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1012', 'Serviço profissional hospitalar não é coberto pelo plano do beneficiário.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1013', 'Cadastro do beneficiário com problemas.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1014', 'Beneficiário com data de exclusão.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1015', 'Idade do beneficiário acima idade limite.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1016', 'Beneficiário com atendimento suspenso.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1017', 'Data validade da carteira vencida.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1018', 'Empresa do beneficiário suspensa / excluída.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1019', 'Família do beneficiário com atendimento suspenso.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1020', 'Via de cartão do beneficiário cancelada.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1021', 'Via de cartão do beneficiário não liberada.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1022', 'Via de cartão do beneficiário não compatível.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1023', 'Nome do titular inválido.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1024', 'Plano não existente.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1025', 'Beneficiário não possui cobertura para assistência odontológica.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1101', 'Quantidade de guias informadas no protocolo diferente das cadastradas.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1102', 'Protocolo é de reapresentação.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1103', 'Protocolo não é de reapresentação.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1104', 'Valor total do protocolo diferente do valor total das guias.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1201', 'Atendimento fora da vigência do contrato com o credenciado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1202', 'Número do CNES inválido.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1203', 'Código prestador inválido.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1204', 'Admissão anterior à inclusão do credenciado na rede.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1205', 'Admissão após o desligamento do credenciado da rede.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1206', 'CPF/CNPJ inválido.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1207', 'Credenciado não pertence à rede credenciada.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1208', 'Solicitação anterior à inclusão do credenciado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1209', 'Solicitação após o desligamento do credenciado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1210', 'Solicitante credenciado não cadastrado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1211', 'Assinatura / carimbo do credenciado inexistente.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1212', 'Atendimento / referência fora da vigência do contrato do prestador.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1213', 'CBO (especialidade) inválido.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1214', 'Credenciado não habilitado a realizar o procedimento.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1215', 'Credenciado fora da abrangência geográfica do plano.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1216', 'Especialidade não cadastrada.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1217', 'Especialidade não cadastrada para o prestador.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1218', 'Código de prestador incompatível com procedimento / exame cobrado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1301', 'Tipo guia inválido.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1302', 'Código tipo guia principal e número guias incompatíveis.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1303', 'Não existe o número guia principal informado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1304', 'Cobrança em guia indevida.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1305', 'Item pago em outra guia.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1306', 'Não existe número guia principal e/ou código guia principal.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1307', 'Número da guia inválido.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1308', 'Guia já apresentada.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1309', 'Procedimento contratado não está de acordo com o tipo de guia utilizado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1310', 'Serviço do tipo cirúrgico e invasivo. Equipe médica não informada na guia.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1311', 'Prestador executante não informado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1312', 'Prestador contratado não informado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1313', 'Guia com rasura.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1314', 'Guia sem assinatura e/ou carimbo do credenciado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1315', 'Guia sem data do ato cirúrgico.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1316', 'Guia com local de atendimento preenchido incorretamente.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1317', 'Guia sem data do atendimento.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1318', 'Guia com código de serviço preenchido incorretamente.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1319', 'Guia sem assinatura do assistido.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1320', 'Identificação do assistido incompleta.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1321', 'Validade da guia expirada.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1322', 'Comprovante presencial ou GTO não enviado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1323', 'Data preenchida incorretamente.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1401', 'Acomodação não autorizada.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1402', 'Procedimento não autorizado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1403', 'Não existe informação sobre a senha de autorização do procedimento.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1404', 'Não existe guia de autorização relacionada.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1405', 'Data de validade da senha é anterior à data do atendimento.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1406', 'Número da senha informado diferente do liberado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1407', 'Serviço solicitado não possui cobertura.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1408', 'Quantidade serviço solicitada acima da autorizada.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1409', 'Quantidade serviço solicitada acima coberta.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1410', 'Serviço solicitado em carência.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1411', 'Solicitante não informado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1412', 'Problemas no sistema autorizador.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1413', 'Acomodação não possui cobertura.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1414', 'Data de validade da senha expirada.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1415', 'Procedimento não autorizado para o beneficiário.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1416', 'Solicitante não cadastrado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1417', 'Solicitante não habilitado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1418', 'Solicitante suspenso.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1419', 'Serviço solicitado já autorizado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1420', 'Serviço solicitado fora da cobertura.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1421', 'Serviço solicitado é de pré-existência.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1422', 'Especialidade não cadastrada para o solicitante.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1423', 'Quantidade solicitada acima da quantidade permitida.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1424', 'Quantidade autorizada acima da quantidade permitida.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1425', 'Necessita pré-autorização da empresa.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1426', 'Não autorizado pela auditoria médica.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1427', 'Necessidade de auditoria médica.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1428', 'Falta de autorização da empresa de conectividade.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1429', 'CBO-s (especialidade) não autorizado a realizar o serviço.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1430', 'Procedimento odontológico não autorizado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1431', 'Procedimento não autorizado na face solicitada.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1432', 'Procedimento não autorizado para dente/região solicitada.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1433', 'Procedimento não autorizado, dente ausente.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1434', 'Cobrança de conta de CTI neonatal na senha do parto.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1435', 'Vigência do acordo posterior à data de realização do procedimento.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1436', 'Cancelamento do acordo anterior à data de realização do procedimento.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1437', 'Senha de autorização cancelada.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1438', 'Procedimento solicitado não autorizado por não atender a diretriz de utilização (DUT) do rol de procedimentos e eventos em saúde da ANS.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1501', 'Tempo de evolução da doença inválido.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1502', 'Tipo de doença inválido.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1503', 'Indicador de acidente inválido.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1504', 'Caráter de internação inválido.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1505', 'Regime da internação inválido.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1506', 'Tipo de internação inválido.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1507', 'Urgência não aplicável.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1508', 'Código CID não informado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1509', 'Código CID inválido.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1601', 'Reincidência no atendimento.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1602', 'Tipo de atendimento inválido ou não informado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1603', 'Tipo de consulta inválido.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1604', 'Tipo de saída inválido.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1605', 'Intervenção anterior à admissão.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1606', 'Final da intervenção anterior ao início da intervenção.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1607', 'Alta hospitalar anterior ao final da intervenção.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1608', 'Alta anterior à data de internação.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1609', 'Motivo saída inválido.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1610', 'Óbito mulher inválido.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1611', 'Intervenção anterior a internação.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1612', 'Serviço não pode ser realizado no local especificado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1613', 'Consulta não autorizada.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1614', 'Serviço ambulatorial não autorizado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1615', 'Internação não autorizada.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1701', 'Cobrança fora do prazo de validade.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1702', 'Cobrança de procedimento em duplicidade.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1703', 'Horário do atendimento não está na faixa de urgência/emergência.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1704', 'Valor cobrado superior ao acordado em pacote.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1705', 'Valor apresentado a maior.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1706', 'Valor apresentado a menor.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1707', 'Não existe informação sobre a tabela que será utilizada na valoração. Verifique o contrato do prestador.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1708', 'Não existe valor para o procedimento realizado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1709', 'Falta prescrição médica.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1710', 'Falta visto da enfermagem.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1711', 'Procedimento pertence a um pacote acordado e já cobrado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1712', 'Assinatura do médico responsável pelo exame inexistente.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1713', 'Faturamento inválido.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1714', 'Valor do serviço superior ao valor de tabela.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1715', 'Valor do serviço inferior ao valor de tabela.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1716', 'Percentual de redução/acréscimo fora dos valores definidos em tabela.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1717', 'Pago conforme relatório de auditoria externa - conta inicial.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1718', 'Reanálise negada, pago conforme relatório auditoria.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1719', 'Reanálise negada, análise conforme tabela acordada.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1720', 'Liberados 150% de vídeo, sem cobertura para adicional de acomodação.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1721', 'Código cobrado substituído pelo código pago.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1722', 'Pago conforme negociação.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1723', 'Adicional de urgência não previsto para atendimento clínico.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1724', 'Visita médica cobrada pela equipe cirúrgica incluída no período de 10 dias após realização do procedimento cirúrgico.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1725', 'Valor pago a maior referente à taxa administrativa.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1726', 'Valor apresentado a maior - plano individual.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1727', 'Pago valor compatível com o procedimento.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1728', 'Cobrança de material incluso no procedimento / exame realizado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1729', 'Cobrança de material com valor acima do permitido para procedimento/exame realizado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1730', 'Filme incluso no exame realizado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1731', 'Taxa incompatível para atendimento ambulatorial.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1732', 'QT com data de evento divergente da liberada.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1733', 'Recuperação de valores por pagamento indevido.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1734', 'Cobrado conta aberta, pago o pacote conforme negociação.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1735', 'Cobrança de pacote não negociado com o prestador.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1736', 'Conta aguardando negociação para pagamento.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1737', 'Diferença deve ser cobrada do beneficiário pelo prestador como franquia.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1738', 'Documento fiscal não enviado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1739', 'Duplicidade de conta devido a período cobrado já efetuado em outra parcial.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1740', 'Estorno do valor de procedimento pago.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1741', 'Honorário ou procedimento já pago a outro prestador.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1742', 'Honorário ou procedimento já pago por reembolso ao beneficiário.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1743', 'Não há negociação para cobrança do kit, discriminar por itens.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1744', 'Negociação diferenciada devido a liminar.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1745', 'Pagamento da equipe conforme relatório do cirurgião.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1746', 'Percentual de acréscimo diferente do negociado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1747', 'Plano do beneficiário e o tipo de acomodação não permitem acréscimo de honorários.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1748', 'Procedimento não caracteriza urgência/emergência.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1749', 'Relatório de auditoria não enviado na conta.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1801', 'Procedimento inválido.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1802', 'Procedimento incompatível com o sexo do beneficiário.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1803', 'Idade do beneficiário incompatível com o procedimento.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1804', 'Número de dias liberados / sessões autorizadas não informadas.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1805', 'Valor total do procedimento diferente do valor processado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1806', 'Quantidade de procedimento deve ser maior que zero.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1807', 'Procedimentos médicos duplicados.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1808', 'Procedimento não conforme com CID.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1809', 'Cobrança de procedimento não executado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1810', 'Cobrança de procedimento não solicitado pelo médico.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1811', 'Procedimento sem registro de execução.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1812', 'Cobrança de procedimento não correlacionado ao relatório específico.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1813', 'Cobrança de procedimento sem justificativa para realização ou com justificativa insuficiente.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1814', 'Cobrança de procedimento com data de autorização posterior à do atendimento.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1815', 'Procedimento não autorizado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1816', 'Cobrança de procedimento em quantidade incompatível com o procedimento/evolução clínica.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1817', 'Cobrança de procedimento incluso no procedimento principal.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1818', 'Cobrança de procedimento que exige autorização prévia.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1819', 'Cobrança de procedimento com história clínica/hipótese diagnóstica não compatível.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1820', 'Cobrança de procedimento em quantidade acima da máxima permitida/autorizada.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1821', 'Cobrança de procedimento não compatível com a idade.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1822', 'Cobrança de procedimento com ausência de resultado ou laudo técnico.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1823', 'Procedimento realizado pelo mesmo profissional, na mesma especialidade, no prazo inferior ao estipulado sem justificativa adequada.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1824', 'Procedimento cobrado não corresponde ao exame executado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1825', 'Cobrança de procedimento ambulatorial com data de autorização posterior à do atendimento.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1826', 'Vias de acesso dos procedimentos cobrados não estão previstas na listagem de procedimentos múltiplos.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1827', 'Cobrança de outro procedimento em outra guia, na mesma data, pelo mesmo profissional com mesmo grau de participação - liberado valor referente à via de acesso do procedimento secundário.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1828', 'Adicional de urgência não previsto para procedimento cirúrgico eletivo.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1829', 'Adicional de vídeo não previsto para o procedimento.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1830', 'Cobrança de procedimento sem informação das datas de atendimento- visita, plantão, intensivista, avaliação enteral/parenteral.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1831', 'Laudo do exame enviado não justifica a cobrança do procedimento.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1832', 'Procedimento não permite cobrança de auxiliar de anestesista.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1833', 'Procedimento cobrado não permite acréscimo de acomodação.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1834', 'Porte anestésico cobrado incompatível com o porte do procedimento realizado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1835', '"Analgesia por dia subsequente" não justificada em relatório médico, para o procedimento realizado e/ou data do atendimento.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1836', '"Analgesia por dia subsequente" incompatível com a via de administração do medicamento - vo ou iv periférica - sendo liberada visita hospitalar.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1837', 'Não cabe pagamento do honorário integral por ser via de acesso cirúrgico diferente.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1838', 'Grau de participação informado incompatível com evento cobrado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1839', 'Necessário envio do resultado do exame anátomo patológico.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1840', 'Procedimento executado antes da autorização.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1901', 'Acomodação inválida.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1902', 'Acomodação informada não está de acordo com acomodação contratada.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1903', 'Permanência hospitalar incompatível com a evolução clínica.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1904', 'Permanência hospitalar incompatível com o procedimento autorizado');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1905', 'Quantidade de diárias deve ser maior que zero.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1906', 'Acomodação não informada.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1907', 'Quantidade UTI não prevista para procedimento.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1908', 'Usuário não possui cobertura de UTI.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1909', 'Acomodação não autorizada.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1910', 'Cobrança de diárias em locais de acomodações diferentes, no mesmo dia.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1911', 'Permanência hospitalar para investigação injustificada.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1912', 'Evolução clínica não compatível com a permanência em UTI.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1913', 'Código de diária incompatível com o local de atendimento.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1914', 'Cobrança de diária em quantidade incompatível com a permanência hospitalar.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1915', 'Mudança de acomodação sem comunicação ao paciente, familiar ou acompanhante, ou sem solicitação destes.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1916', 'Cobrança de diárias de UTI incompatível com diagnóstico e evolução clínica.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1917', 'Falta prorrogação para quantidade de diárias cobradas.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('1918', 'Plano do beneficiário não contempla diária de acompanhante.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2001', 'Material inválido.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2002', 'Material sem cobertura para atendimento ambulatorial.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2003', 'Material não especificado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2004', 'Material sem nota fiscal do fornecedor.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2005', 'Quantidade de material deve ser maior que zero.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2006', 'Material informado não coberto.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2007', 'Cobrança de material em quantidade incompatível com a permanência.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2008', 'Cobrança de material em quantidades incompatíveis com o procedimento realizado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2009', 'Quantidade de material superior à quantidade coberta.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2010', 'Cobrança de materiais inclusos nas taxas.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2011', 'Cobrança de material incluso no pacote negociado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2012', 'Cobrança de material incompatível com o relatório técnico.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2013', 'Cobrança de material em permanência hospitalar não autorizada.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2014', 'Cobrança de material não utilizado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2015', 'Material não autorizado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2101', 'Medicamento inválido.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2102', 'Medicamento sem cobertura para atendimento ambulatorial.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2103', 'Medicamento não especificado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2104', 'Medicamento sem nota fiscal do fornecedor.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2105', 'Quantidade de medicamentos deve ser maior que zero.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2106', 'Medicamento informado não coberto.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2107', 'Cobrança de medicamento em quantidade incompatível com a permanência.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2108', 'Cobrança de medicamento em quantidades incompatíveis com o procedimento realizado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2109', 'Quantidade de medicamento superior à quantidade coberta.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2110', 'Cobrança de medicamentos inclusos nas taxas.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2111', 'Cobrança de medicamento incluso no pacote negociado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2112', 'Cobrança de medicamento incompatível com o relatório técnico.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2113', 'Cobrança de medicamento em permanência hospitalar não autorizada.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2114', 'Cobrança de medicamento não utilizado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2115', 'Medicamento não autorizado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2201', 'OPME inválido.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2202', 'OPME sem cobertura para atendimento ambulatorial.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2203', 'OPME sem nota fiscal do fornecedor.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2204', 'Quantidade de OPME deve ser maior que zero.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2205', 'OPME informado não coberto.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2206', 'OPME informado não autorizado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2207', 'Cobrança de OPME não utilizado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2208', 'Cobrança de OPME no item material e medicamentos.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2209', 'Cobrança de OPME em desacordo com relatório técnico.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2210', 'Cobrança de OPME em quantidade incompatível com o procedimento realizado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2211', 'Cobrança de OPME inclusa no pacote.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2212', 'OPME em desacordo com os critérios técnicos adotados pela operadora.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2213', 'OPME pago a fornecedor terceirizado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2301', 'Gases medicinais inválidos.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2302', 'Cobrança de oxigenoterapia sem prescrição médica.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2303', 'Cobrança de oxigenoterapia com quantitativo de uso em divergência/pago valor corrigido.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2304', 'Cobrança de oxigênio incluso na taxa de nebulização especificada.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2305', 'Cobrança de oxigenoterapia em uso prolongado sem justificativa de uso.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2306', 'Cobrança de oxigenoterapia sem registro de controle de uso (entrada e saída).');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2307', 'Cobrança de gases em quantidade superior ao período de permanência.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2308', 'Cobrança de co2 nas cirurgias videolaparoscópicas durante toda a realização do procedimento (início ao fim).');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2309', 'Cobrança de ar comprimido sem registro no boletim anestésico e duração de uso.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2310', 'Cobrança de gases incompatível com o utilizado/ prescrito.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2401', 'Taxa / aluguel inválido.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2402', 'Cobrança de taxa por uso de equipamento incompatível com o procedimento realizado/uso previsto no procedimento.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2403', 'Cobrança de taxa de uso de bomba de infusão em paciente internado na UTI.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2404', 'Cobrança de outras taxas associadas/inclusas na cobrança da taxa de sala prevista.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2405', 'Cobrança de mais de uma taxa de sala de cirurgia, por conta do número de procedimentos realizados no mesmo tempo cirúrgico.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2406', 'Cobrança indevida de taxa de sala por administração de medicamentos.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2407', 'Cobrança de taxas, de serviços realizados em ambientes incompatíveis com o uso de equipamentos.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2408', 'Cobrança de taxas em quantidade superior ao tempo de permanência hospitalar.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2409', 'Cobrança de taxa de observação em pronto socorro com permanência menor que o período estipulado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2410', 'Cobrança de taxa de observação em pronto socorro sem o registro da permanência.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2411', 'Cobrança de taxa de sala de pronto socorro, para aplicação de medicamentos.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2412', 'Cobrança de taxa de recuperação anestésica não justificada para o procedimento.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2413', 'Cobrança de taxa inclusa no pacote negociado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2414', 'Cobrança de taxa de equipamento em concomitância com a cobrança de taxa para o procedimento.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2415', 'Taxa exige informação do valor na guia.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2416', 'Cobrança de taxa de recuperação anestésica para pacientes com pós- operatório imediato realizado na UTI/CTI.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2417', 'Cobrança de taxa de recuperação anestésica sem a presença do anestesista.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2418', 'Cobrança de taxa de sala incompatível com o procedimento.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2419', 'Cobrança de taxa de observação para atendimento que gerou uma internação.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2420', 'Cobrança de taxa de sala cirúrgica com porte anestésico diferente do procedimento autorizado/realizado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2421', 'Cobrança de taxa em quantidade incorreta.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2422', 'Cobrança de taxa por uso de equipamento de uso obrigatório na sala de cirurgia, cuja taxa de sala cirúrgica já inclui seu uso.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2423', 'Cobrança de taxa de equipamentos de uso obrigatório no local de atendimento.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2424', 'Cobrança de taxa de observação para atendimento que gerou uma internação.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2501', 'Procedimento em série inválido.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2502', 'Cobrança de duas avaliações fisioterápicas.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2503', 'Cobrança de psicoterapia individual, quando o aplicado é a cobrança de psicoterapia em grupo.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2504', 'Quantidade de sessões cobradas não condizem com as assinaturas no controle de tratamento seriado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2505', 'O código cobrado é diferente do código autorizado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2506', 'A quantidade de sessões cobradas é diferente da quantidade autorizada.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2507', 'O código autorizado está incompatível com a prescrição médica solicitada.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2508', 'Cobrança de sessões sem o devido plano de tratamento e, ou, com o prazo de pagamento expirado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2509', 'Cobrança do procedimento seriado incompatível com o quadro clínico.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2510', 'Cobrança do procedimento seriado em número de sessões acima da quantidade estabelecida.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2511', 'Ausência de evolução no prontuário médico do tratamento seriado realizado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2512', 'Cobrança de sessões de fisioterapia em desacordo com as evoluções do prontuário médico.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2513', 'Cobrança de tratamento seriado sem justificativa clínica/técnica.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2514', 'Serviço não contratado para o prestador.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2515', 'Local de atendimento inadequado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2516', 'Quantidade cobrada diferente da realizada.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2601', 'Codificação incorreta/inadequada do procedimento.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2602', 'Cobrança de honorário incluso no procedimento principal.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2603', 'Cobrança de honorário sem registro da efetiva participação do profissional.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2604', 'Procedimento principal não requer equipe médica.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2605', 'Não cabe pagamento do honorário integral por ser a mesma via de acesso cirúrgico.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2606', 'Cobrança do honorário em local de atendimento incorreto (inexistente).');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2607', 'Cobrança de honorários em duplicidade.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2608', 'Cobrança de consulta indevida, quando o procedimento principal já está sendo remunerado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2609', 'Local de atendimento não informado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2610', 'Grau de participação de auxiliar incompatível com procedimento cobrado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2611', 'Cobrança de especialista não justificada no evento.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2612', 'Cobrança indevida de equipe "stand-by", já que angioplastia seguida de cirurgia cardíaca.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2613', 'Honorário médico do anestesista já liberado no procedimento cirúrgico, pois "analgesia por dia subsequente" cobrada na mesma data do evento cirúrgico.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2614', 'Cobrança de cada participante da equipe deve ser feita em guias diferentes.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2701', 'Procedimento inválido.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2702', 'Cobrança de exame não solicitado pelo médico.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2703', 'Exame sem registro de execução.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2704', 'Cobrança de exame não correlacionado ao relatório específico.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2705', 'Cobrança de procedimento/exame sem justificativa para realização ou com justificativa insuficiente.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2706', 'Cobrança de procedimento/exame com data de autorização posterior à do atendimento.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2707', 'Exame não autorizado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2708', 'Cobrança de exame em quantidade incompatível com o procedimento/evolução clínica.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2709', 'Cobrança de procedimento incluso no procedimento principal.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2710', 'Cobrança de exame que exige autorização prévia.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2711', 'Cobrança de exame com história clínica/hipótese diagnóstica não compatível.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2712', 'Cobrança de exame em quantidade acima da máxima permitida/autorizada.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2713', 'Cobrança de exame não compatível com a idade.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2714', 'Cobrança de exame com ausência de resultado ou laudo técnico.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2715', 'Exame realizado pelo mesmo profissional, na mesma especialidade, no prazo inferior ao estipulado sem justificativa adequada.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2716', 'Exame cobrado não corresponde ao exame executado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2717', 'Cobrança de exame ambulatorial com data de autorização posterior à do atendimento.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2718', 'Exames não justificam caráter de urgência.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2801', 'Pacote inválido.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2802', 'Pacote incompatível com o sexo do beneficiário.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2803', 'Idade do beneficiário incompatível com o pacote.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2804', 'Valor total do pacote diferente do valor processado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2805', 'Valor do pacote superior ao valor dos itens.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2806', 'Cobrança de pacote não executado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2807', 'Cobrança de pacote não solicitado pelo médico.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2808', 'Pacote sem registro de execução.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2809', 'Cobrança de pacote não correlacionado ao relatório específico.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2810', 'Cobrança de pacote sem justificativa para realização ou com justificativa insuficiente.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2811', 'Cobrança de pacote com data de autorização posterior à do atendimento.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2812', 'Pacote não autorizado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2813', 'Cobrança de pacote em quantidade incompatível com o procedimento/evolução clínica.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2814', 'Itens de composição do pacote não realizados.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2815', 'Cobrança do pacote exige autorização prévia.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2816', 'Cobrança de pacote com história clínica/hipótese diagnóstica não compatível.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2817', 'Cobrança de pacote em quantidade acima da máxima permitida/autorizada.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2818', 'Cobrança de pacote não compatível com a idade.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2819', 'Cobrança de pacote com ausência de resultado ou laudo técnico.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2820', 'Pacote realizado pelo mesmo profissional, na mesma especialidade, no prazo inferior ao estipulado sem justificativa adequada.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2821', 'Pacote cobrado não corresponde ao exame executado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2822', 'Cobrança de pacote ambulatorial com data de autorização posterior à do atendimento.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2901', 'Revisão de glosa inválida.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2902', 'Glosa mantida.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2903', 'Pedido de revisão sem justificativa.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2904', 'Mais de um recurso de glosa para a mesma guia/protocolo.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2905', 'A guia não é de revisão.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2906', 'Número da guia inválido.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2907', 'Prazo de 180 dias ultrapassado para solicitação de reanálise.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2908', 'Solicitação de reanálise efetuada de forma incorreta.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('2909', 'Prazo para solicitação de recurso de glosa prescrito.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3001', 'Procedimento odontológico inválido.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3002', 'Cobrança de procedimento odontológico que exige autorização prévia.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3003', 'Idade do beneficiário incompatível com o procedimento odontológico.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3004', 'Cobrança de procedimento odontológico em quantidade acima da máxima permitida/autorizada.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3005', 'Valor total do procedimento diferente do valor processado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3006', 'Quantidade de procedimento deve ser maior que zero.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3007', 'Procedimentos odontológicos duplicados.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3008', 'Cobrança de procedimento odontológico incluso no procedimento principal.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3009', 'Cobrança de procedimento odontológico não executado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3010', 'Cobrança de procedimento não solicitado pelo cirurgião-dentista.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3011', 'Procedimento odontológico sem registro de execução.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3012', 'Cobrança de procedimento odontológico não correlacionado ao relatório específico.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3013', 'Cobrança de procedimento odontológico sem justificativa para realização ou com justificativa insuficiente.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3014', 'Cobrança de procedimento odontológico com data de autorização posterior à do atendimento.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3015', 'Cobrança de procedimento odontológico com ausência de resultado ou laudo técnico.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3016', 'Procedimento odontológico realizado pelo mesmo profissional, na mesma especialidade, no prazo inferior ao estipulado sem justificativa adequada.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3017', 'Procedimento cobrado não corresponde a perícia (especificar).');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3018', 'Evento glosado por auditoria (especificar)');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3019', 'Evento sob análise técnica, aguardando liberação de confirmação para posterior pagamento.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3020', 'Conforme documentação radiográfica enviada, evento realizado inadequadamente.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3021', 'Falha em informação de dados de arcadas/hemi-arcos.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3022', 'Falha em informação de dados de dente inicial e/ou final.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3023', 'Falha em informação de dados de faces dos dentes.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3024', 'Evento só possível em dentes decíduos.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3025', 'Evento só possível em dentes permanentes.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3026', 'Erro nas informações de ordem dos dentes inicial e final.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3027', 'Desacordo entre o tipo de dente e o número de canais solicitados.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3028', 'Evento restrito à especialistas.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3029', 'Evento não indicado pela auditoria inicial.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3030', 'Auditoria final consta que a restauração foi realizada em outro material.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3031', 'Radiografia fora dos padrões técnicos.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3032', 'Intervalo da última MPP inferior a três meses.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3033', 'Intervalo da última MPP inferior a quatro meses.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3034', 'Justificativa tecnicamente não satisfatória.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3035', 'Paciente em tratamento com o mesmo profissional.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3036', 'Paciente em tratamento com outro profissional.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3037', 'Procedimento cobrado não é igual ao executado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3038', 'Radiografia inicial incongruente com a radiografia final.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3039', 'Radiografia não corresponde ao procedimento cobrado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3040', 'Glosa técnica (especificar detalhadamente).');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3041', 'Aguardando documentação de ortodontia.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3042', 'Após análise da radiografia inicial verificou-se exodontia de incluso.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3043', 'Após análise da radiografia inicial verificou-se exodontia de semi-incluso.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3044', 'Após análise da radiografia inicial verificou-se exodontia simples.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3045', 'Após análise da radiografia inicial, verificou-se exodontia de fragmento radicular.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3046', 'Auditoria final consta que o procedimento foi realizado com outro material.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3047', 'Ausência de imagem/foto/radiografia/ diagnóstico pós-procedimento odontológico.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3048', 'Cancelamento do procedimento odontológico por solicitação do beneficiário.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3049', 'Cancelamento do procedimento odontológico por solicitação do prestador.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3050', 'Cobrança de urgência/emergência na vigência do tratamento odontológico.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3051', 'Documentação em análise.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3052', 'Documentação incompleta, incorreta ou ausente.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3053', 'Elementos podem ser visualizados em uma mesma película.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3054', 'Identificado conduto(s) não obturado(s).');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3055', 'Identificado tratamento endodôntico e não retratamento.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3056', 'Na auditoria foi constatada divergência na quantidade de faces restauradas.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3057', 'Não apresenta a quantidade mínima de elementos dentários por segmento.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3058', 'Necessária auditoria final.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3059', 'Necessária auditoria inicial.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3060', 'Necessária auditoria intermediária.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3061', 'Necessária avaliação do especialista.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3062', 'Necessário enviar laudo ou relatório técnico sobre o tratamento solicitado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3063', 'O plano de tratamento autorizado será cancelado devido à troca de profissional.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3064', 'Procedimento autorizado apenas para dentes tratados endodonticamente.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3065', 'Procedimento autorizado somente para dentes anteriores.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3066', 'Procedimento em desacordo com o anexo guia tratamento odontológico situação inicial.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3067', 'Radiografia final não enviada.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3068', 'Radiografia final sem dissociação dos condutos.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3069', 'Radiografia indica a necessidade de tratamento endodôntico.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3070', 'Radiografia indica a presença de raiz residual no alvéolo.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3071', 'Radiografia indica ausência de núcleo.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3072', 'Radiografia indica canal (ais) não obturado(s).');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3073', 'Radiografia indica desvio da trajetória do canal.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3074', 'Radiografia indica excesso de material.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3075', 'Radiografia indica falha na obturação do(s) conduto(s).');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3076', 'Radiografia indica falta de adaptação da coroa/núcleo.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3077', 'Radiografia indica falta de adaptação da coroa/peça protética.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3078', 'Radiografia indica núcleo inadequado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3079', 'Radiografia indica tratamento endodôntico e não retratatamento endodôntico.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3080', 'Radiografia inicial e final não enviada.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3081', 'Radiografia inicial não enviada.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3082', 'Radiografia/imagem indica falha na restauração.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3083', 'Reavaliar o plano de tratamento observando critérios de indicação, oportunidade e viabilidade.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3084', 'Relatório analise técnica sem carimbo/assinatura do prestador.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3085', 'Radiografia não corresponde ao procedimento solicitado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('3086', 'Tratamento odontológico não caracterizado como urgência.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('5001', 'Mensagem eletrônica fora do Padrão TISS.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('5002', 'Não foi possível validar o arquivo XML.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('5003', 'Endereço do remetente inválido.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('5004', 'Endereço do destinatário inválido.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('5005', 'Remetente não identificado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('5006', 'Destinatário não identificado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('5007', 'Mensagem inconsistente ou incompleta.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('5008', 'Espaço reservado para a caixa de saída insuficiente.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('5009', 'Espaço reservado para a caixa de entrada insuficiente.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('5010', 'Envio de mensagem não foi terminado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('5011', 'Envio de mensagem finalizada.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('5012', 'Recebimento de mensagem não finalizado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('5013', 'Recebimento de mensagem finalizada.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('5014', 'Código HASH inválido. Mensagem pode estar corrompida.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('5015', 'Número de guias/demonstrativos dentro da mensagem superior ao tamanho máximo permitido.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('5016', 'Sem nenhuma ocorrência de movimento de inclusão na competência para envio a ANS.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('5017', 'Arquivo processado pela ANS.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('5018', 'Certificado digital inválido.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('5019', 'Certificado digital vencido.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('5020', 'Certificado digital revogado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('5021', 'Cadeia de certificação inválida.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('5022', 'Assinatura digital não confere.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('5023', 'Competência não está liberada para envio de dados.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('5024', 'Operadora inativa na competência dos dados.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('5025', 'Data de registro da transação inválida.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('5026', 'Hora de registro da transação inválida.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('5027', 'Registro ANS da operadora inválido.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('5028', 'Versão do padrão inválida.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('5029', 'Indicador inválido.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('5030', 'Código do munícipio inválido.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('5031', 'Caráter de atendimento inválido.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('5032', 'Indicador de recém-nato inválido.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('5033', 'Motivo de encerramento inválido.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('5034', 'Valor não informado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('5035', 'Código da tabela de referência não informado.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('5036', 'Código do grupo do procedimento inválido.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('5037', 'Código do dente inválido.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('5038', 'Código da região da boca inválido.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('5039', 'Código da face do dente inválido.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('5040', 'Valor deve ser maior que zero.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('5041', 'Quantidade não informada.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('5042', 'Valor informado da guia diferente do somatório do valor informado dos itens.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('5043', 'Motivo inválido.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('5044', 'Já existem informações na ANS para a competência informada.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('5045', 'Competência anterior não enviada.');
INSERT INTO motivosGlosa (codigo, descricao) VALUES ('5046', 'Competência inválida.');
