CREATE TABLE `insightsIA` (
	`id` int AUTO_INCREMENT NOT NULL,
	`arquivoId` int NOT NULL,
	`comparacaoId` int,
	`estabelecimentoId` int,
	`convenioId` int,
	`tipoInsight` enum('item_faltante','quantidade_baixa','quantidade_alta','valor_divergente','item_incomum','padrao_incompleto','oportunidade_cobranca') NOT NULL,
	`severidade` enum('baixa','media','alta') NOT NULL DEFAULT 'media',
	`titulo` varchar(255) NOT NULL,
	`descricao` text NOT NULL,
	`guiaNumero` varchar(100),
	`codigoProcedimento` varchar(50),
	`descricaoProcedimento` varchar(255),
	`codigoItemSugerido` varchar(50),
	`descricaoItemSugerido` varchar(255),
	`quantidadeSugerida` decimal(10,2),
	`valorEstimado` decimal(12,2),
	`quantidadeAtual` decimal(10,2),
	`quantidadeEsperada` decimal(10,2),
	`valorAtual` decimal(12,2),
	`valorEsperado` decimal(12,2),
	`confianca` int DEFAULT 50,
	`padraoId` int,
	`status` enum('pendente','aceito','rejeitado','ignorado') NOT NULL DEFAULT 'pendente',
	`feedbackUsuario` text,
	`processadoPor` int,
	`dataProcessamento` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `insightsIA_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `padroesCobranca` (
	`id` int AUTO_INCREMENT NOT NULL,
	`convenioId` int,
	`estabelecimentoId` int,
	`codigoProcedimentoPrincipal` varchar(50) NOT NULL,
	`descricaoProcedimentoPrincipal` varchar(255),
	`tipoProcedimentoPrincipal` varchar(50),
	`itensAssociados` json NOT NULL,
	`totalOcorrencias` int NOT NULL DEFAULT 1,
	`valorMedioConta` decimal(12,2),
	`valorMinConta` decimal(12,2),
	`valorMaxConta` decimal(12,2),
	`confianca` int DEFAULT 50,
	`status` enum('aprendendo','ativo','revisao','inativo') NOT NULL DEFAULT 'aprendendo',
	`validadoPor` int,
	`dataValidacao` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `padroesCobranca_id` PRIMARY KEY(`id`)
);
