CREATE TABLE `conciliacaoTasy` (
	`id` int AUTO_INCREMENT NOT NULL,
	`estabelecimentoId` int NOT NULL,
	`mesReferencia` int NOT NULL,
	`anoReferencia` int NOT NULL,
	`convenioId` int,
	`dadoTasyId` int,
	`demonstrativoItemId` int,
	`guiaTasy` varchar(100),
	`atendimentoTasy` varchar(50),
	`codigoTasy` varchar(50),
	`descricaoTasy` text,
	`quantidadeTasy` decimal(10,4),
	`valorTasy` decimal(12,4),
	`dataTasy` timestamp,
	`pacienteTasy` varchar(255),
	`guiaDemo` varchar(100),
	`codigoDemo` varchar(50),
	`descricaoDemo` text,
	`quantidadeDemo` decimal(10,4),
	`valorPagoDemo` decimal(12,4),
	`valorGlosadoDemo` decimal(12,4),
	`motivoGlosaDemo` text,
	`dataDemo` timestamp,
	`pacienteDemo` varchar(255),
	`statusConciliacao` enum('conciliado','divergencia_valor','divergencia_quantidade','nao_encontrado_demo','nao_encontrado_tasy','glosado','pago_parcial') NOT NULL DEFAULT 'conciliado',
	`diferencaValor` decimal(12,4),
	`diferencaQuantidade` decimal(10,4),
	`observacao` text,
	`processadoPor` int,
	`dataProcessamento` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `conciliacaoTasy_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `demonstrativoItens` (
	`id` int AUTO_INCREMENT NOT NULL,
	`estabelecimentoId` int NOT NULL,
	`arquivoId` int NOT NULL,
	`convenioId` int NOT NULL,
	`codigo` varchar(50),
	`descricao` text,
	`quantidade` decimal(10,4) DEFAULT '1',
	`valorUnitario` decimal(12,4),
	`valorTotal` decimal(12,4),
	`valorPago` decimal(12,4),
	`valorGlosado` decimal(12,4),
	`motivoGlosa` text,
	`codigoGlosa` varchar(20),
	`status` enum('pago','glosado','pago_parcial') NOT NULL DEFAULT 'pago',
	`guiaNumero` varchar(100),
	`dataExecucao` timestamp,
	`dataReferencia` timestamp,
	`pacienteNome` varchar(255),
	`pacienteCarteirinha` varchar(100),
	`nomeMedico` varchar(255),
	`crmMedico` varchar(50),
	`tipoDespesa` enum('gas','medicamento','material','diaria','taxa','procedimento','outros') DEFAULT 'procedimento',
	`dadosExtras` json,
	`procedimentoOrigemId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `demonstrativoItens_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `resumoConciliacaoTasy` (
	`id` int AUTO_INCREMENT NOT NULL,
	`estabelecimentoId` int NOT NULL,
	`mesReferencia` int NOT NULL,
	`anoReferencia` int NOT NULL,
	`convenioId` int,
	`totalItensTasy` int DEFAULT 0,
	`valorTotalTasy` decimal(15,2),
	`totalItensDemo` int DEFAULT 0,
	`valorTotalPago` decimal(15,2),
	`valorTotalGlosado` decimal(15,2),
	`itensConciliados` int DEFAULT 0,
	`itensDivergentes` int DEFAULT 0,
	`itensNaoEncontradosDemo` int DEFAULT 0,
	`itensNaoEncontradosTasy` int DEFAULT 0,
	`itensGlosados` int DEFAULT 0,
	`valorDiferenca` decimal(15,2),
	`percentualRecebido` decimal(5,2),
	`percentualGlosado` decimal(5,2),
	`dataProcessamento` timestamp,
	`processadoPor` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `resumoConciliacaoTasy_id` PRIMARY KEY(`id`)
);
