CREATE TABLE `contasTasy` (
	`id` int AUTO_INCREMENT NOT NULL,
	`estabelecimentoId` int NOT NULL,
	`importacaoId` int NOT NULL,
	`nrInternoConta` varchar(50) NOT NULL,
	`guia` varchar(100),
	`atendimento` varchar(50),
	`dataFaturado` timestamp,
	`convenio` varchar(255),
	`paciente` varchar(255),
	`dataConta` timestamp,
	`setor` varchar(255),
	`protocolo` varchar(100),
	`statusProtocolo` varchar(50),
	`totalProcedimentos` int DEFAULT 0,
	`valorTotalProcedimentos` decimal(15,4),
	`totalMatMed` int DEFAULT 0,
	`valorTotalMatMed` decimal(15,4),
	`valorTotalConta` decimal(15,4),
	`status` enum('aberta','faturada','paga','glosada','parcial') DEFAULT 'faturada',
	`valorPago` decimal(15,4),
	`valorGlosado` decimal(15,4),
	`dataPagamento` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `contasTasy_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `itensContaTasy` (
	`id` int AUTO_INCREMENT NOT NULL,
	`contaTasyId` int NOT NULL,
	`tipoItem` enum('procedimento','material','medicamento') NOT NULL,
	`itemOriginalId` int NOT NULL,
	`codigo` varchar(50),
	`descricao` text,
	`quantidade` decimal(10,4),
	`valorUnitario` decimal(12,4),
	`valorTotal` decimal(12,4),
	`medico` varchar(255),
	`crm` varchar(50),
	`statusPagamento` enum('pendente','pago','glosado','parcial') DEFAULT 'pendente',
	`valorPago` decimal(12,4),
	`valorGlosado` decimal(12,4),
	`motivoGlosa` text,
	`codigoGlosa` varchar(50),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `itensContaTasy_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `matMedTasy` (
	`id` int AUTO_INCREMENT NOT NULL,
	`estabelecimentoId` int NOT NULL,
	`importacaoId` int NOT NULL,
	`atendimento` varchar(50) NOT NULL,
	`nrInternoConta` varchar(50),
	`guia` varchar(100),
	`sequencia` varchar(50),
	`dataFaturado` timestamp,
	`convenio` varchar(255),
	`paciente` varchar(255),
	`dataConta` timestamp,
	`codigo` varchar(50),
	`codigoConvenio` varchar(50),
	`descricao` text,
	`quantidade` decimal(10,4),
	`unidade` varchar(20),
	`valorUnitario` decimal(12,4),
	`valorTotal` decimal(12,4),
	`setor` varchar(255),
	`protocolo` varchar(100),
	`statusProtocolo` varchar(50),
	`tipoItem` enum('material','medicamento') DEFAULT 'material',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `matMedTasy_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `procedimentosTasy` (
	`id` int AUTO_INCREMENT NOT NULL,
	`estabelecimentoId` int NOT NULL,
	`importacaoId` int NOT NULL,
	`atendimento` varchar(50) NOT NULL,
	`nrInternoConta` varchar(50),
	`guia` varchar(100),
	`sequencia` varchar(50),
	`dataFaturado` timestamp,
	`convenio` varchar(255),
	`paciente` varchar(255),
	`dataConta` timestamp,
	`codigo` varchar(50),
	`codigoConvenio` varchar(50),
	`descricao` text,
	`quantidade` decimal(10,4),
	`unidade` varchar(20),
	`valorUnitario` decimal(12,4),
	`valorTotal` decimal(12,4),
	`setor` varchar(255),
	`protocolo` varchar(100),
	`statusProtocolo` varchar(50),
	`medico` varchar(255),
	`funcaoMedico` varchar(100),
	`crm` varchar(50),
	`valorMedico` decimal(12,4),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `procedimentosTasy_id` PRIMARY KEY(`id`)
);
