CREATE TABLE `faturadoTasy` (
	`id` int AUTO_INCREMENT NOT NULL,
	`estabelecimentoId` int NOT NULL,
	`importacaoId` int NOT NULL,
	`sequencia` varchar(50),
	`convenio` varchar(255),
	`competencia` varchar(20),
	`protocolo` varchar(100),
	`setor` varchar(255),
	`atend` varchar(50),
	`conta` varchar(50),
	`profExec` varchar(255),
	`cdMotivoExcConta` varchar(50),
	`dsComplMotivoExcon` text,
	`tipoItem` enum('PROC/TAXA','MAT/MED') NOT NULL,
	`cdItem` varchar(50),
	`cdItemTuss` varchar(50),
	`dtItem` timestamp,
	`descricao` text,
	`qtd` decimal(10,4),
	`vlFaturado` decimal(12,4),
	`aReceber` decimal(12,4),
	`vlPago` decimal(12,4),
	`vlGlosa` decimal(12,4),
	`motivoGlosa` text,
	`retorno` varchar(50),
	`dtPgto` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `faturadoTasy_id` PRIMARY KEY(`id`)
);
