CREATE TABLE `recebimento_tiss` (
	`id` int AUTO_INCREMENT NOT NULL,
	`arquivo_id` int,
	`numero_demonstrativo` varchar(20),
	`nome_operadora` varchar(150),
	`cnpj_operadora` varchar(20),
	`data_emissao` timestamp,
	`numero_lote_prestador` varchar(20),
	`numero_protocolo` varchar(20),
	`situacao_protocolo` varchar(5),
	`numero_guia_prestador` varchar(20),
	`numero_guia_operadora` varchar(20),
	`senha` varchar(20),
	`numero_carteira` varchar(20),
	`situacao_guia` varchar(5),
	`sequencial_item` int,
	`data_realizacao` timestamp,
	`codigo_tabela` varchar(5),
	`codigo_procedimento` varchar(15),
	`descricao_procedimento` varchar(255),
	`valor_informado` decimal(12,2),
	`valor_processado` decimal(12,2),
	`valor_liberado` decimal(12,2),
	`qtd_executada` int,
	`codigo_glosa` varchar(10),
	`descricao_glosa` text,
	`data_importacao` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `recebimento_tiss_id` PRIMARY KEY(`id`)
);
