CREATE TABLE `Tasy_maternidadeela_atendimentos_stagion` (
	`id` int AUTO_INCREMENT NOT NULL,
	`estabelecimentoId` int NOT NULL,
	`configId` int,
	`numeroAtendimento` varchar(50),
	`tipoSaida` varchar(100),
	`local` varchar(255),
	`paciente` varchar(255),
	`carater` varchar(50),
	`dataAdmissao` timestamp,
	`dataAlta` timestamp,
	`tipoAtendimento` varchar(100),
	`servico` varchar(255),
	`procedimentoPrincipal` varchar(255),
	`centroCusto` varchar(100),
	`dadosBrutos` json,
	`criadoEm` timestamp DEFAULT (now()),
	`atualizadoEm` timestamp DEFAULT (now()),
	`convenio` varchar(255),
	`dsCategoria` varchar(255),
	`dsPlano` varchar(255),
	`competencia` varchar(20),
	`referencia` varchar(20),
	`protTasy` varchar(50),
	`nomeProtocolo` varchar(255),
	`protConv` varchar(100),
	`dtEntrega` timestamp,
	`protStatus` varchar(50),
	`titulo` varchar(100),
	`dtTitulo` timestamp,
	`dataVencimento` timestamp,
	`dsSetorEntrada` varchar(255),
	`dsSetorLeito` varchar(255),
	`etapaConta` varchar(255),
	`setorEtapa` varchar(255),
	`dtEtapa` timestamp,
	`userEtapa` varchar(100),
	`motivoDevolucao` text,
	`conta` varchar(50),
	`autorizacao` varchar(100),
	`matricula` varchar(100),
	`sexo` varchar(10),
	`idade` varchar(50),
	`codServico` varchar(50),
	`procedimentoPrincipal2` varchar(500),
	`dataInicio` varchar(20),
	`dataFim` varchar(20),
	`dsMotivoAlta` varchar(255),
	`medicoResp` varchar(255),
	`crm` varchar(50),
	`valorConta` decimal(15,2),
	CONSTRAINT `Tasy_maternidadeela_atendimentos_stagion_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `TASY_hemolabor_atendimentos_stagion` (
	`id` int AUTO_INCREMENT NOT NULL,
	`estabelecimentoId` int NOT NULL,
	`configId` int,
	`numeroAtendimento` varchar(50),
	`tipoSaida` varchar(100),
	`local` varchar(255),
	`paciente` varchar(255),
	`carater` varchar(50),
	`dataAdmissao` timestamp,
	`dataAlta` timestamp,
	`tipoAtendimento` varchar(100),
	`servico` varchar(255),
	`procedimentoPrincipal` varchar(255),
	`centroCusto` varchar(100),
	`dadosBrutos` json,
	`criadoEm` timestamp DEFAULT (now()),
	`atualizadoEm` timestamp DEFAULT (now()),
	`convenio` varchar(255),
	`dsCategoria` varchar(255),
	`dsPlano` varchar(255),
	`competencia` varchar(20),
	`referencia` varchar(20),
	`protTasy` varchar(50),
	`nomeProtocolo` varchar(255),
	`protConv` varchar(100),
	`dtEntrega` timestamp,
	`protStatus` varchar(50),
	`titulo` varchar(100),
	`dtTitulo` timestamp,
	`dataVencimento` timestamp,
	`dsSetorEntrada` varchar(255),
	`dsSetorLeito` varchar(255),
	`etapaConta` varchar(255),
	`setorEtapa` varchar(255),
	`dtEtapa` timestamp,
	`userEtapa` varchar(100),
	`motivoDevolucao` text,
	`conta` varchar(50),
	`autorizacao` varchar(100),
	`matricula` varchar(100),
	`sexo` varchar(10),
	`idade` varchar(50),
	`codServico` varchar(50),
	`procedimentoPrincipal2` varchar(500),
	`dataInicio` varchar(20),
	`dataFim` varchar(20),
	`dsMotivoAlta` varchar(255),
	`medicoResp` varchar(255),
	`crm` varchar(50),
	`valorConta` decimal(15,2),
	CONSTRAINT `TASY_hemolabor_atendimentos_stagion_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
DROP TABLE `tasy_atendimentos_staging`;--> statement-breakpoint
CREATE INDEX `idx_tasy_matela_estab` ON `Tasy_maternidadeela_atendimentos_stagion` (`estabelecimentoId`);--> statement-breakpoint
CREATE INDEX `idx_tasy_matela_config` ON `Tasy_maternidadeela_atendimentos_stagion` (`configId`);--> statement-breakpoint
CREATE INDEX `idx_tasy_hemolabor_estab` ON `TASY_hemolabor_atendimentos_stagion` (`estabelecimentoId`);--> statement-breakpoint
CREATE INDEX `idx_tasy_hemolabor_config` ON `TASY_hemolabor_atendimentos_stagion` (`configId`);