CREATE TABLE `tasy_faturado_staging` (
	`id` int AUTO_INCREMENT NOT NULL,
	`importacaoId` int,
	`estabelecimentoId` int,
	`estabelecimento` varchar(255),
	`sequencia` varchar(100),
	`convenio` varchar(255),
	`prod` varchar(100),
	`competencia` varchar(20),
	`dtReferencia` varchar(50),
	`entrega` varchar(50),
	`protocolo` varchar(100),
	`nrProtocolo` varchar(100),
	`nrTitulo` varchar(100),
	`nmUsuario` varchar(255),
	`dtAtualizacao` varchar(50),
	`statusProt` varchar(100),
	`tipoProt` varchar(100),
	`docConvenio` varchar(100),
	`atend` varchar(50),
	`entrada` varchar(50),
	`stEntrada` varchar(100),
	`conta` varchar(50),
	`autorizacao` varchar(100),
	`senha` varchar(100),
	`dtInicio` varchar(50),
	`dtFim` varchar(50),
	`encerramento` varchar(50),
	`matricula` varchar(100),
	`paciente` varchar(255),
	`cdMotivoExcConta` varchar(100),
	`dsComplMotivoExcon` text,
	`tipo` varchar(100),
	`tipoItem` varchar(100),
	`setor` varchar(255),
	`profExec` varchar(255),
	`crm` varchar(50),
	`cdItem` varchar(50),
	`cdItemTuss` varchar(50),
	`dtItem` varchar(50),
	`descricao` text,
	`credito` varchar(10),
	`qtd` varchar(20),
	`valoresRaw` text,
	`vlProduzido` decimal(14,2),
	`vlMedico` decimal(14,2),
	`aReceber` decimal(14,2),
	`vlPago` decimal(14,2),
	`vlGlosa` decimal(14,2),
	`vlAmaior` decimal(14,2),
	`tReceb` decimal(14,2),
	`motivoGlosa` text,
	`retorno` varchar(50),
	`pgto` varchar(20),
	`dtPgto` varchar(50),
	`linhaOriginal` int,
	`parseStatus` enum('ok','ambiguo','erro') NOT NULL DEFAULT 'ok',
	`parseNotas` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `tasy_faturado_staging_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE INDEX `idx_tfs_importacao` ON `tasy_faturado_staging` (`importacaoId`);--> statement-breakpoint
CREATE INDEX `idx_tfs_estab` ON `tasy_faturado_staging` (`estabelecimentoId`);--> statement-breakpoint
CREATE INDEX `idx_tfs_convenio` ON `tasy_faturado_staging` (`convenio`);--> statement-breakpoint
CREATE INDEX `idx_tfs_competencia` ON `tasy_faturado_staging` (`competencia`);--> statement-breakpoint
CREATE INDEX `idx_tfs_sequencia` ON `tasy_faturado_staging` (`sequencia`);--> statement-breakpoint
CREATE INDEX `idx_tfs_conta` ON `tasy_faturado_staging` (`conta`);--> statement-breakpoint
CREATE INDEX `idx_tfs_atend` ON `tasy_faturado_staging` (`atend`);--> statement-breakpoint
CREATE INDEX `idx_tfs_parse_status` ON `tasy_faturado_staging` (`parseStatus`);