CREATE TABLE `Tasy_relatorio_financeiro_stagion` (
	`id` int AUTO_INCREMENT NOT NULL,
	`estabelecimentoId` int NOT NULL,
	`configId` int,
	`estabelecimento` varchar(50),
	`sequencia` varchar(100),
	`convenio` varchar(255),
	`prod` varchar(20),
	`competencia` varchar(20),
	`dtReferencia` datetime,
	`entrega` datetime,
	`protocolo` varchar(100),
	`nrProtocolo` varchar(100),
	`nrTitulo` varchar(100),
	`nmUsuario` varchar(100),
	`dtAtualizacao` datetime,
	`statusProt` varchar(50),
	`tipoProt` varchar(50),
	`docConvenio` varchar(100),
	`atend` varchar(100),
	`entrada` varchar(20),
	`stEntrada` varchar(255),
	`conta` varchar(100),
	`autorizacao` varchar(100),
	`senha` varchar(100),
	`dtInicio` datetime,
	`dtFim` datetime,
	`encerramento` varchar(20),
	`matricula` varchar(100),
	`paciente` varchar(255),
	`cdMotivoExcConta` varchar(100),
	`dsComplMotivoExcon` varchar(500),
	`tipo` varchar(50),
	`tipoItem` varchar(50),
	`setor` varchar(255),
	`profExec` varchar(255),
	`crm` varchar(50),
	`cdItem` varchar(50),
	`cdItemTuss` varchar(50),
	`dtItem` datetime,
	`descricao` text,
	`credito` varchar(50),
	`qtd` decimal(12,4),
	`vlProduzido` decimal(15,2),
	`vlMedico` decimal(15,2),
	`aReceber` decimal(15,2),
	`vlPago` decimal(15,2),
	`vlGlosa` decimal(15,2),
	`vlAMaior` decimal(15,2),
	`tReceb` decimal(15,2),
	`motivoGlosa` text,
	`retorno` varchar(100),
	`pgto` varchar(20),
	`dtPgto` datetime,
	`hashId` varchar(255),
	`dadosBrutos` json,
	`criadoEm` timestamp DEFAULT (now()),
	`atualizadoEm` timestamp DEFAULT (now()),
	CONSTRAINT `Tasy_relatorio_financeiro_stagion_id` PRIMARY KEY(`id`),
	CONSTRAINT `idx_tasy_finstg_hashid` UNIQUE(`hashId`)
);
--> statement-breakpoint
CREATE INDEX `idx_tasy_finstg_estab` ON `Tasy_relatorio_financeiro_stagion` (`estabelecimentoId`);--> statement-breakpoint
CREATE INDEX `idx_tasy_finstg_config` ON `Tasy_relatorio_financeiro_stagion` (`configId`);--> statement-breakpoint
CREATE INDEX `idx_tasy_finstg_conta` ON `Tasy_relatorio_financeiro_stagion` (`conta`);--> statement-breakpoint
CREATE INDEX `idx_tasy_finstg_comp` ON `Tasy_relatorio_financeiro_stagion` (`competencia`);--> statement-breakpoint
CREATE INDEX `idx_tasy_finstg_dtitem` ON `Tasy_relatorio_financeiro_stagion` (`dtItem`);
