export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  ownerEmail: process.env.OWNER_EMAIL ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  pgAtendimentosHost: process.env.PG_ATENDIMENTOS_HOST ?? "",
  pgAtendimentosPort: process.env.PG_ATENDIMENTOS_PORT ?? "5432",
  pgAtendimentosDatabase: process.env.PG_ATENDIMENTOS_DATABASE ?? "",
  pgAtendimentosUser: process.env.PG_ATENDIMENTOS_USER ?? "",
  pgAtendimentosPassword: process.env.PG_ATENDIMENTOS_PASSWORD ?? "",
  warleineDbHost: process.env.WARLEINE_DB_HOST ?? "",
  warleineDbPort: process.env.WARLEINE_DB_PORT ?? "5432",
  warleineDbName: process.env.WARLEINE_DB_NAME ?? "",
  warleineDbUser: process.env.WARLEINE_DB_USER ?? "",
  warleineDbPassword: process.env.WARLEINE_DB_PASSWORD ?? "",
  smtpHost: process.env.SMTP_HOST ?? "",
  smtpPort: process.env.SMTP_PORT ?? "587",
  smtpUser: process.env.SMTP_USER ?? "",
  smtpPass: process.env.SMTP_PASS ?? "",
  smtpFrom: process.env.SMTP_FROM ?? "",
};
