export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  pgAtendimentosHost: process.env.PG_ATENDIMENTOS_HOST ?? "",
  pgAtendimentosPort: process.env.PG_ATENDIMENTOS_PORT ?? "5432",
  pgAtendimentosDatabase: process.env.PG_ATENDIMENTOS_DATABASE ?? "",
  pgAtendimentosUser: process.env.PG_ATENDIMENTOS_USER ?? "",
  pgAtendimentosPassword: process.env.PG_ATENDIMENTOS_PASSWORD ?? "",
};
